### PR TITLE
lint: fix camelCase

### LINKED ISSUE #547: lint: fix issues
I open this issue to discuss CML's coding convention change and tasks needed to perform such change.

@0x2b3bfa0 @casperdcl @shcheklein

### PR DESCRIPTION
**Pull request by casperdcl**
fixes #547

- The first commit is programmatically generated.
  - [ ] NB: don't squash-merge (to keep bot commit separate)
- deDe-camel
- The actual commits to check are https://github.com/iterative/cml/compare/7741a6f...6b28b84?w=1. In particular, my handling of:
  - `rm-watermark`
  - `commit-sha`
  - `mime-type`
  - `head-sha`
  - `user-name`
  - `user-email`
  - `gitlab-uploads`
  - `startup-script`
  - `ssh-private`
  - `spot-price`
  - `idle-timeout`
  - `hdd-size`
  - `cloud-ssh-private-visible`
  - `pipe-args`
  - `git-url-parse`
  - `tf-resource`

which is annoying due to https://github.com/yargs/yargs/issues/1679

[Snake is dead. Snake? Snake! SNAKE!](https://youtu.be/VzLDg0RaiTU?t=137)

### CODE REVIEW

File: src/terraform.js [hunk 1]
```diff
@@ -101,16 +101,16 @@ resource "iterative_cml_runner" "runner" {
...
   ${gpu ? `instance_gpu = "${gpu}"` : ''}
-  ${hdd_size ? `instance_hdd_size = ${hdd_size}` : ''}
-  ${ssh_private ? `ssh_private = "${ssh_private}"` : ''}
+  ${hddSize ? `instance_hdd_size = ${hddSize}` : ''}
+  ${sshPrivate ? `ssh_private = "${sshPrivate}"` : ''}
   ${spot ? `spot = ${spot}` : ''}
-  ${spot_price ? `spot_price = ${spot_price}` : ''}
-  ${startup_script ? `startup_script = "${startup_script}"` : ''}
+  ${spotPrice ? `spot_price = ${spotPrice}` : ''}
+  ${startupScript ? `startup_script = "${startupScript}"` : ''}
```
Comment (casperdcl) [inline src/terraform.js:108]: PS do these have to remain `snake_case`? Not sure what `resource iterative_cml_runner` is used for.

Comment (0x2b3bfa0) [reply src/terraform.js:108]: That's a Terraform template for cloud provisioning, and snake_case should be preserved in the [HCL](https://github.com/hashicorp/hcl) identifiers. The JavaScript counterparts can be dromedaryCase though. It's fine as-is.

We should probably use [Terraform CDK](https://www.hashicorp.com/blog/cdk-for-terraform-enabling-python-and-typescript-support) instead, but that's a separate discussion.

File: bin/cml-runner.js [hunk 2]
```diff
@@ -72,116 +72,116 @@ const shutdown = async (opts) => {
...
+      cloud_ssh_private: sshPrivate,
       cloud_spot: spot,
-      cloud_spot_price: spot_price,
-      cloud_startup_script: startup_script,
-      tf_file,
+      cloud_spot_price: spotPrice,
+      cloud_startup_script: startupScript,
+      tfFile,
       workdir
     } = opts;
```
Comment (0x2b3bfa0) [inline bin/cml-runner.js:140]: I think that `opts` come in snake case just because of [`decamelize-keys`](https://www.npmjs.com/package/decamelize-keys) 🤔

**Comment by 0x2b3bfa0** [comment]
Definitely out of scope for this pull request, but function, method and variable names seem to follow slightly different conventions: `verbNoun()` / `nounVerb()` / `verbNn()` sorted by perceived pertinence.

File: bin/cml-runner.js (hunk 2 above)
Comment (casperdcl) [reply bin/cml-runner.js:140]: :facepalm:

File: src/cml.test.js [hunk 3]
```diff
@@ -173,28 +173,28 @@ describe('Gitlab tests', () => {
...
     try {
       const report = '## Test comment';
-      const commit_sha = 'invalid_sha';
+      const commitSha = 'invalid_sha';
 
-      await new CML({ repo: REPO }).comment_create({ report, commit_sha });
+      await new CML({ repo: REPO }).commentCreate({ report, commitSha });
     } catch (err) {
-      catched_err = err.message;
+      caughtErr = err.message;
```
Comment (DavidGOrtega) [inline src/cml.test.js:195]: 😆

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]
lets try /tests first

File: bin/cml-runner.js [hunk 4]
```diff
@@ -72,116 +72,116 @@ const shutdown = async (opts) => {
...
+      idle_timeout: idleTimeout,
       name,
       single,
       cloud,
       cloud_region: region,
       cloud_type: type,
       cloud_gpu: gpu,
-      cloud_hdd_size: hdd_size,
-      cloud_ssh_private: ssh_private,
+      cloud_hdd_size: hddSize,
```
[the remark this answers is not in the document]
Comment (casperdcl) [reply bin/cml-runner.js]: yup, dedecamlled now.

**Comment by casperdcl** [comment]
Where's this `--tf_resource` flag from? https://gitlab.com/iterative.ai/cml/-/jobs/1283674644#L7031

**Comment by 0x2b3bfa0** [comment]
> _Where's this --tf_resource flag from?_

You've discovered the arcanes of the Terraform Provider 🧙🏼‍♂️

**Comment by 0x2b3bfa0** [comment]
The provider is tightly coupled to CML, so we need to preserve backwards compatibility with the old underscore option for now.

File: bin/cml-runner.js [hunk 5]
```diff
@@ -308,98 +306,96 @@ const run = async (opts) => {
...
+    'cloud-spot-price',
+    'Maximum spot instance bidding price in USD. Defaults to the current spot bidding price'
+  )
+  .default('cloud-startup-script', '')
+  .describe(
+    'cloud-startup-script',
+    'Run the provided Base64-encoded Linux shell script during the instance initialization'
+  )
+  .default('tf-resource')
+  .hide('tf-resource')
```
Comment (0x2b3bfa0) [inline bin/cml-runner.js:397]:
```suggestion
  .default('tf-resource')
  .hide('tf-resource')
  .alias('tf-resource', 'tf_resource')`
```

Something like that until we release a new CML version. Then, we can release the provider with the update and remove the underscore variant.

Comment (casperdcl) [reply bin/cml-runner.js:397]: :monocle_face: 
```suggestion
  .default('tf-resource')
  .hide('tf-resource')
  .alias('tf-resource', 'tf_resource')
```

Comment (0x2b3bfa0) [reply bin/cml-runner.js:397]: Sorry, @casperdcl. Typing backticks with my keyboard layout on macOS is far from being a pleasant experience. 🤦🏼

Comment (casperdcl) [reply bin/cml-runner.js:397]: hmm, still failing though (might not be related)

**Comment by 0x2b3bfa0** [comment]
🤔  Still failing... Don't be scared by the enormous amount of system logs on failure:

```
May 21 15:55:04 ip-172-31-20-73 cml.sh[20072]: Error: Failed preparing Gitlab runner: Forbidden
```

**Comment by DavidGOrtega** [comment]
@casperdcl 

.default('tf_resource')
.hide('tf_resource')

the parameter is hidden and should be aliased also.

**Comment by DavidGOrtega** [comment]
Test are failing on GL Im checking them

**Comment by casperdcl** [comment]
@DavidGOrtega this is good enough:

```js
  .default('tf-resource')
  .hide('tf-resource')
  .alias('tf-resource', 'tf_resource')
```

It doesn't need an additional `.hide('tf_resource')` (try running `--help` locally or also see the passing tests which don't show `tf*resource` in the output)

**Comment by DavidGOrtega** [comment]
> @DavidGOrtega this is good enough:
> 
> ```js
>   .default('tf-resource')
>   .hide('tf-resource')
>   .alias('tf-resource', 'tf_resource')
> ```
> 
> It doesn't need an additional `.hide('tf_resource')` (try running `--help` locally or also see the passing tests which don't show `tf*resource` in the output)

Yeah, alias works one or the other.
This change is very critiical and we have to test it through-fully if not the runner wont destroy the machine and the provider has to be released with the two choices. If not images or actions not aligned (cml-setup pinned to specific versiion ) wont work. @0x2b3bfa0

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, the provider will **always** invoke the latest CML, be it through [the latest container for Kubernetes](https://github.com/iterative/terraform-provider-iterative/pull/114/files#diff-08560ef5459da3ede56dd9700b81f84384dbff1de69918854a2b8e2da0155155R63 ) or [the latest package](https://github.com/iterative/terraform-provider-iterative/blob/cf42d8aca03c846eb70b67530d1d3b29e1577b8f/iterative/resource_runner.go#L282) for any other vendor:

**Comment by DavidGOrtega** [comment]
> @DavidGOrtega, the provider will **always** invoke the latest CML when calling the `cml-runner` command, be it through [the latest container for Kubernetes](https://github.com/iterative/terraform-provider-iterative/pull/114/files#diff-08560ef5459da3ede56dd9700b81f84384dbff1de69918854a2b8e2da0155155R63) or [the latest package](https://github.com/iterative/terraform-provider-iterative/blob/cf42d8aca03c846eb70b67530d1d3b29e1577b8f/iterative/resource_runner.go#L282) for any other vendor:

I have tried and it simply wont work the provider breaking the workflow.
The issue that I say is that an user can be using a pinned CML and invoking the last terraform provider from the registry generating a bad tf (unknown param)

**Comment by casperdcl** [comment]
Does this mean we *have* to continue to use `.default('tf_resource')` with no alias?

**Comment by 0x2b3bfa0** [comment]
> Does this mean we _have_ to continue to use `.default('tf_resource')` with no alias?

Absolutely not! 🙀  This alias is completely harmless.

**Comment by 0x2b3bfa0** [comment]
> I have tried and it simply wont work the provider breaking the workflow.

I would be glad to know more details about the error you're getting.

> The issue that I say is that an user can be using a pinned CML and invoking the last terraform provider from the registry generating a bad tf (unknown param)

What I mean is that the provider doesn't offer any means for users to pin the CML version that's being invoked in the cloud instance: it will always be the latest one.

**Comment by DavidGOrtega** [comment]
@casperdcl @0x2b3bfa0 tf_resource is a private input. Its meant to be for us not the user. They do not use it.
Also what I say is that the main.tf file generated old CMLs are going th generate it with tf_resource instead tf-resource

**Comment by DavidGOrtega** [comment]
> What I mean is that the provider doesn't offer any means for users to pin the CML version that's being invoked in the cloud instance: it will always be the latest one.

@0x2b3bfa0 not really. setup-cml allows you to pin the version. And indeed that was what saved that user in Discord after 0.4.1

**Comment by 0x2b3bfa0** [comment]
> Also what I say is that the main.tf file generated old CMLs are going th generate it with tf_resource instead tf-resource breaking the workflow if we release this with

As per my understanding, this option is only being used [here](https://github.com/iterative/terraform-provider-iterative/blob/cf42d8aca03c846eb70b67530d1d3b29e1577b8f/iterative/resource_runner.go#L319) and we control the `cml-runner` version that receives it; always the latest version. Do generated `main.tf` files include any mention to this option?

**Comment by 0x2b3bfa0** [comment]
> setup-cml allows you to pin the version

🤔  But... that doesn't have anything to do with the cloud-facing CML version that we use for launching `cml-runner` remotely, right?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 
cml-runner --cloud -> main.tf -> terraform init -> cml-runner
If cml-runner --cloud v=0.4.2 
main.tf  contains tf_resource not tf-resource breaking terraform init 

😅

**Comment by 0x2b3bfa0** [comment]
> _main.tf contains tf_resource not tf-resource breaking terraform init_

That's what I struggle to understand: the `main.tf` file does not contain any reference to this parameter, at least on my environment.

```hcl
terraform {
  required_providers {
    iterative = {
      source = "iterative/iterative"
    }
  }
}

provider "iterative" {}


resource "iterative_cml_runner" "runner" {
  repo = "https://github.com/···"
  token = "ghp_···"
  driver = "github"
  labels = "cml-runner"
  idle_timeout = 300
  name = "cml-vbb4zjk8f8"

  cloud = "aws"
  region = "us-west"
  instance_type = "g3.4xlarge"

  instance_hdd_size = 64


  spot_price = -1

}
```

**Comment by DavidGOrtega** [comment]
Its true, I removed that from the cml-runner command

**Review by 0x2b3bfa0 — APPROVED** [review]
Looks good to me, including https://github.com/iterative/cml/pull/554/commits/fc5a0abf6e43a879c0420cf5569928143f5e544a!

File: src/cml.js [hunk 6]
```diff
@@ -199,47 +199,41 @@ class CML {
...
+  async runnersByLabels(opts = {}) {
+    return await getDriver(this).runnersByLabels(opts);
   }
 
-  async repo_token_check() {
-    try {
-      await this.runner_token();
-    } catch (err) {
-      throw new Error(
-        'REPO_TOKEN does not have enough permissions to access workflow API'
```
Comment (DavidGOrtega) [inline src/cml.js:227]: Why remove it?

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 
> Looks good to me, including fc5a0ab!

why fc5a0ab looks good?
It have saved a decent amount of headaches in the past.
A common GITHUB_TOKEN can access the api but not the workflows api. Is the token is not set it CML will tell first and if the token is set major error, having into account that GITHUB_TOKEN is the default token that is probably set, is that the token has no rights to do that. If not set that way is the error descriptive enough for us just to know or at least to hint it?

**Comment by 0x2b3bfa0** [comment]
The issue with the current approach is that we're outputting the following message no matter what the actual error is:
```
Error: REPO_TOKEN does not have enough permissions to access workflow API
```

Removing the catch-all block, we would get instead this slightly more opaque message in the case you describe:
```
RequestError [HttpError]: Resource not accessible by integration
```

It's not as explicit as the previous message, but at leaset it won't mask unrelated errors behind the same description.

**Comment by casperdcl** [comment]
Ah fyi I don't intend to include fc5a0abf in this PR (will revert and leave for another issue) - it was a debug commit and clearly failed as I later realised that the `/ tests` command incorrectly uses an NPM-relese rather than the current state of the code so completely ignores fc5a0abf anyway. Which is yet another issue to be addressed elsewhere.

In any case the `/ tests` command appears to be commented as:

https://github.com/iterative/cml/blob/3cbbce00f90065205c6bf32685ee15774d50e55f/.github/workflows/checkbot.yml#L6

in which case it is successful (the docker image does indeed build successfully, and the later failure is unrelated to this PR).

I propose to merge without fc5a0abf. Any objections?

File: src/cml.js (hunk 6 above)
Comment (casperdcl) [reply src/cml.js:227]: debug commit removed

**Comment by DavidGOrtega** [comment]
> The issue with the current approach is that we're outputting the following message no matter what the actual error is:

As I say the most probable error at that point specially in the CI is that. The CI is going to provide always a GITHUB_TOKEN.

We could make the question or suggest the error like many others do to hint.

```
This normally means .... or Does your token have workflow permissions?
```

But as I say its going to be very rare that the error is not that. It even always telling you the truth.
If you miss to setup a proper token its correctly telling you that the token, even incorrect one, has to permissions to do such thing

**Review by DavidGOrtega — APPROVED** [review]
Caan we please squash and merge? :pray:

**Comment by casperdcl** [comment]
@DavidGOrtega I've removed that debug commit (we should leave it for another issue) - have you reviewed and are you happy with this PR as-is?

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]
tf-resource what happened to it?

**Review by DavidGOrtega — APPROVED** [review]
👍
