### PR TITLE
Revert conditional chaining

### LINKED ISSUE #960: Getting a syntax error while executing cml on CLI
I installed CML using

```
sudo npm i -g @dvcorg/cml
```

but getting this error whenever I execute any CML commands.

```
>> cml ci --help
/usr/lib/node_modules/@dvcorg/cml/src/drivers/bitbucket_cloud.js:383
        responseBody?.error?.message || responseBody?.error || responseBody;
                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:11:24)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Is there a proper way to test whether the installation has been done correctly?

### LINKED ISSUE #965: Node 16 change is controversial
### Why  
- Its breaking workflows 

### Solutions
 - transpile
 - revert (not possible due to the new publish feature in BB
 - write a line of code uglier

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Fixes #960 & closes #965. Is ~ugly as a sin~ moderately ugly, thanks to @DavidGOrtega's suggestion.

### Before
```javascript
const error =
        responseBody?.error?.message || responseBody?.error || responseBody;
throw new Error(`${response.statusText} ${error}`.trim());
```
### After
```javascript
const { error } = responseBody.error ?  responseBody : { error: responseBody }
throw new Error(`${response.statusText} ${error.message || error}`.trim());
```

### CODE REVIEW

File: src/drivers/bitbucket_cloud.js [hunk 1]
```diff
@@ -379,8 +379,13 @@ class BitbucketCloud {
...
-      const error =
-        responseBody?.error?.message || responseBody?.error || responseBody;
+      const error = responseBody // FIXME: use conditional chaining when dropping node<16
+        ? responseBody.error
+          ? responseBody.error.message
+            ? responseBody.error.message
+            : responseBody.error
+          : responseBody
+        : responseBody;
       throw new Error(`${response.statusText} ${error}`.trim());
```
Comment (DavidGOrtega) [inline src/drivers/bitbucket_cloud.js:389]:
```suggestion
const { error } = responseBody.error ?  responseBody : { error: responseBody }
throw new Error(`${response.statusText} ${error.message || error}`.trim());
```

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]
Alternative?

**Review by DavidGOrtega — DISMISSED** [review]
👍

**Review by DavidGOrtega — APPROVED** [review]
