### PR TITLE
Fix .git suffix removal logic

### LINKED ISSUE #562: self-hosted runner not connected to my repo.
Hello, I am new to cml community. I am trying to use self-hosted runners with github actions to set up CI with my private github repo. I have pulled the docker container dvcorg/cml-py3 and ran with all the environment variables as specified in this video https://www.youtube.com/watch?v=rVq-SCNyxVc&ab_channel=DVCorgDVCorg 

I have created a personal access token with workflow and repo permissions.

However, when I run this without -d flag, I see an error as follows:

```
{"level":"error","status":"terminated"}
Error: REPO_TOKEN does not have enough permissions to access workflow API
    at CML.repo_token_check (/cml/src/cml.js:236:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	Destroy scheduled: 30 seconds remaining.
	No TF resource found
```
@elleobrien , Can you please take a look and help me understand, what I am doing wrong?

### LINKED ISSUE #566: Repository addresses must not contain the .git suffix
The error on #562 happened because the user configured a repository address with the `.git` suffix (e.g. https://github.com/user/repository.git) as the `RUNNER_REPO` / `--repo` option. It would be nice to clarify this somewhere in a troubleshooting section, if we plan to have it.

Desiderata, part of #514

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Closes #566 and fixes #562 no matter what format the user chooses.

### CODE REVIEW

File: src/cml.js [hunk 1]
```diff
@@ -74,7 +74,10 @@ class CML {
   constructor(opts = {}) {
     const { driver, repo, token } = opts;
 
-    this.repo = uri_no_trailing_slash(repo || git_remote_url());
+    this.repo = uri_no_trailing_slash(repo || git_remote_url()).replace(
+      /\.git$/,
```
Comment (DavidGOrtega) [inline src/cml.js:78]: nice! much better and safe than it was

**Review by DavidGOrtega — APPROVED** [review]
👍

**Review by casperdcl — APPROVED** [review]
