### PR TITLE
GH runner auto update

### LINKED ISSUE #676: Unexpected stop of container build [CML, AWS, github]
My scenario:
I'm trying to create appropriate pipeline for my ML project. I'm using the following CML yaml file:
```
on:
  # Trigger the workflow on push or pull request
  push:
    branches:
      - mybranch

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on EC2
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
        run: |
          cml-runner \
              --repo https://github.com/MyCompany/myrepo \
              --token=$PERSONAL_ACCESS_TOKEN \
              --cloud aws \
              --cloud-region us-west-1 \
              --cloud-type=g3.4xlarge \
              --labels=cml-runner \
              --idle-timeout 30
    
  model-training:
    needs: [deploy-runner]
    runs-on: [self-hosted, cml-runner]
    container:
      image: docker://dvcorg/cml:0-dvc1-base1-gpu
      options: --gpus all
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Train model
        env:
          repo_token: ${{ secrets.REPO_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DVC_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DVC_SECRET_KEY }}
          REQUIREMENTS_FILE: 'training/training_req.txt'
        run: |
          export AWS_DEFAULT_REGION=us-east-1
          echo "Install reqs"
          sudo apt update
          sudo apt-get install default-jre scala
          pip install py4j
          pip install --no-cache-dir -e .
          export PYSPARK_PYTHON=python3
          echo "Start CML"
          python3 -m spacy download en_core_web_sm
          echo "Pull data"
          dvc repro
          echo "## Model metrics" > report.md
          cat prepare_data/metrics.txt >> report.md
          cml-send-comment report.md
          

```
As you can notice I used the following image docker://dvcorg/cml:0-dvc1-base1-gpu, but I started receive the following error message:

Screenshot 2021-07-27 at 20 22 31
Screenshot 2021-07-27 at 20 24 36

I can see that container started to build but unexpectedly stopped, and I do not see the reason of this behavior. Actually i did not change anything in my script, and it just stopped work, but earlier I run it successfully. 

Thanks!

### PR DESCRIPTION
**Pull request by DavidGOrtega**
New GH runners restarts after update and we destroy them if they exit the CML wrapper. To avoid that we are always downloading latest.

 - closes #676 
 - adds reason of termination in logs
 - adds GH message logs

### CODE REVIEW

File: src/drivers/github.js [hunk 1]
```diff
@@ -207,9 +208,15 @@ class Github {
         await fs.unlink(runnerCfg);
       } catch (e) {
         const arch = process.platform === 'darwin' ? 'osx-x64' : 'linux-x64';
-        const ver = '2.278.0';
+        const { tag_name: ver } = await (
+          await fetch(
+            'https://api.github.com/repos/actions/runner/releases/latest'
+          )
+        ).json();
```
Comment (casperdcl) [inline src/drivers/github.js:215]: :tada:

File: bin/cml-runner.js [hunk 2]
```diff
@@ -290,7 +298,7 @@ const runLocal = async (opts) => {
   if (parseInt(idleTimeout) !== 0) {
     const watcher = setInterval(() => {
       RUNNER_TIMEOUT_TIMER > idleTimeout &&
-        shutdown(opts) &&
+        shutdown({ ...opts, reason: 'timeout' }) &&
```
Comment (casperdcl) [inline bin/cml-runner.js:301]:
```suggestion
        shutdown({ ...opts, reason: `timeout:${idleTimeout}` }) &&
```

File: bin/cml-runner.js [hunk 3]
```diff
@@ -304,7 +312,7 @@ const runLocal = async (opts) => {
           new Date().getTime() - new Date(job.date).getTime() >
           GH_5_MIN_TIMEOUT
         )
-          shutdown(opts) && clearInterval(watcher);
+          shutdown({ ...opts, reason: '72timeout' }) && clearInterval(watcher);
```
Comment (casperdcl) [inline bin/cml-runner.js:315]:
```suggestion
          shutdown({ ...opts, reason: `timeout:72` }) && clearInterval(watcher);
```

File: bin/cml-runner.js [hunk 4]
```diff
@@ -304,7 +312,7 @@ const runLocal = async (opts) => {
           new Date().getTime() - new Date(job.date).getTime() >
           GH_5_MIN_TIMEOUT
         )
-          shutdown(opts) && clearInterval(watcher);
+          shutdown({ ...opts, reason: `timeout:72` }) && clearInterval(watcher);
```
Comment (casperdcl) [inline bin/cml-runner.js:315]:
```suggestion
          shutdown({ ...opts, reason: `timeout:72h` }) && clearInterval(watcher);
```

**Review by casperdcl — APPROVED** [review]
