### PR TITLE
Fix cml ci pr

### LINKED ISSUE #1106: `cml pr` gives authentication error on Bitbucket with self-hosted runner
I have configured a `REPO_TOKEN` in accordance with the docs, and the basic use case for self-hosted runners works. When using an adapted stage that includes `cml pr`, however, an authentication error is thrown:

```
+ cml pr model/random_forest.joblib
{"level":"error","message":"git fetch --all\n\t\n\tremote: Invalid credentials\nfatal: Authentication failed for 'http://bitbucket.org/iterative-ai/example_model_export_cml.git/'\n","stack":"Error: git fetch --all\n\t\n\tremote: Invalid credentials\nfatal: Authentication failed for 'http://bitbucket.org/iterative-ai/example_model_export_cml.git/'\n\n    at /usr/lib/node_modules/@dvcorg/cml/src/utils.js:24:27\n    at ChildProcess.exithandler (node:child_process:406:5)\n    at ChildProcess.emit (node:events:527:28)\n    at maybeClose (node:internal/child_process:1092:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)"}
```

Pipeline run for reference: https://bitbucket.org/iterative-ai/example_model_export_cml/pipelines/results/12/steps/%7Ba82ed9ae-e499-402a-81e9-9a5fe84e76bf%7D

### PR DESCRIPTION
**Pull request by DavidGOrtega**
- closes #1106

### CODE REVIEW

File: src/drivers/bitbucket_cloud.js [hunk 1]
```diff
@@ -398,26 +398,25 @@ class BitbucketCloud {
...
-    git config --unset http.http://${this.repo
-      .replace('https://', '')
-      .replace('.git', '')}.proxy;
+    git config --unset http.http://${repo.host}${repo.pathname}.proxy;
     git config user.name "${userName || this.userName}" &&
     git config user.email "${userEmail || this.userEmail}" &&
-    git remote set-url origin "${repo.toString()}${
-      repo.toString().endsWith('.git') ? '' : '.git'
-    }"`;
+    git remote set-url ${remote} "${repo.toString()}"`;
```
Comment (dacbd) [inline src/drivers/bitbucket_cloud.js:419]: to confirm; BB does **not** want it with `.git`?

**Review by dacbd — APPROVED** [review]

File: src/drivers/bitbucket_cloud.js (hunk 1 above)
Comment (DavidGOrtega) [reply src/drivers/bitbucket_cloud.js:419]: Yes
