### PR TITLE
Cloud runner terminate improvements

### LINKED ISSUE #407: cml-runner - Better idle mechanism in GH
GH runners sometimes hangs when you cancel the job staying idle and not destroying themselves.
Probably for not finishing the current job not allowing idle to come back.

### LINKED ISSUE #649: Instances intermittently fail to terminate
I've had a couple of instances recently that have failed to terminate. In the most recent case this was with the `--reuse` flag set, having run a series of 8 queued jobs.

The instance is sitting idle, with a timeout of `60s` having passed ten minutes ago. I'll need to terminate the instance manually from the command line.

In the most serious case, I had an instance run for two weeks without terminating. It took so long for us to notice because the instance name did not get set to `cml-*` as usual.

Here's the yml we are using:

```
name: train and evaluate rasa model

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1

      - name: deploy
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          --cloud aws \
          --cloud-region eu-west \
          --cloud-type=c5a.4xlarge \
          --cloud-spot true \
          --labels=cml-runner,voice-control,oms-rasa-2 \
          --idle-timeout 60 \
          --reuse
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: docker://dvcorg/cml:0-dvc2-base1

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8.5'
    - name: Install dependencies
      run: |
        apt-get update -y
        apt-get install make python3-pip virtualenv curl
    - name: cml
      env:
        REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1
      run: |
        python --version
        make virtualenv
        dvc repro
        echo "## Metrics" > report.md
        git fetch --prune
        dvc metrics diff main --show-md | grep "Change\|\-\-\-" >> report.md
        dvc metrics diff main --show-md | grep -E "(intent|entity|action).*weighted" | sort >> report.md
        sed "s/results\///g" -i report.md
        cml-send-comment report.md
        dvc push

    - uses: actions/upload-artifact@v2
      with:
        name: gh-artifact-${{ github.event.pull_request.head.sha }}
        path: |
          report.md
          results
        retention-days: 30
        
    - uses: EndBug/add-and-commit@v7
      if: ${{ github.ref != 'refs/heads/main' }} && ${{ github.ref != 'refs/heads/rasax/prod' }}
      with:
         add: 'dvc.lock --force'
         pull_strategy: 'NO-PULL'
         message: 'chg: dvc repro'

### LINKED ISSUE #650: CML seemingly fails to restart job after AWS Spot instances have been shut down
Hey everyone, 
So I noticed a couple of days ago that CML now has new functionality that allows it to restart workflows if one or more AWS spot runners have been told to shut down. However this doesn't seem to be happening for me. 

A couple of details about our case: 
* Our cloud is AWS 
* We're (as far as i can tell) using the `latest` version of CML to deploy a bunch of runners as shown below. 
```
  deploy_runners:
    name: Deploy Cloud Instances
    needs: [setup_config]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
        with:
          version:  latest

      - name: "Deploy runner on EC2"
        shell: bash
        env:
          repo_token: ${{ secrets.ACCESS_TOKEN_CML }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTING }}
          CASE_NAME: ${{ matrix.case_name }}
          N_RUNNERS: ${{ fromJson(needs.setup_config.outputs.json_string).n_runners }}

        run: |
          for (( i=1; i<=N_RUNNERS; i++ ))
          do
            echo "Deploying runner ${i}"
            cml-runner \
            --cloud aws \
            --cloud-region eu-west-2 \
            --cloud-type=m \
            --cloud-hdd-size 100 \
            --cloud-spot \
            --labels=cml-runner &
          done
          wait
          echo "Deployed ${N_RUNNERS} runners."
```

* The job each runner runs does not use the CML images provided by iterative 
* The job that each runner runs has `continue-on-error` set to `False` (wondering whether that is interfering with cml?) 
```
  run_optimisation:
    continue-on-error: false
    strategy:
      matrix: ${{fromJson(needs.setup_config.outputs.json_string).matrix}}
      fail-fast: true

    runs-on: [self-hosted, "cml-runner"]
    container:
      image: python:3.8.10-slim
      volumes:
          - /dev/shm:/dev/shm
```

### LINKED ISSUE #661: GCP compute instances are not shutdown after idle timeout
First off, thanks for adding GCP support to cml-runner.

While playing around with it, I noticed that my compute engine instances weren't being shutdown/terminated (i.e., VM powered off) or deleted. I experimented with `--idle-timeout` and `--single`, yet neither made a difference. The instance stays alive. This is unexpected given [the following sentence from the docs](https://cml.dev/doc/self-hosted-runners#:~:text=After%20the%20job%20runs%2C%20the%20instance%20automatically%20shuts%20down.) on self-hosted runners:

> After the job runs, the instance automatically shuts down.

And indeed, that's what I've observed with AWS instances. Those seem to terminate correctly.

Here's my Github workflow for extra context:

```
name: 'Train-in-the-cloud-GCP'
on: 
  workflow_dispatch:

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: 'Deploy runner on GCP'
        shell: bash
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          # Notice use of `GOOGLE_APPLICATION_CREDENTIALS_DATA` instead of
          # `GOOGLE_APPLICATION_CREDENTIALS`. Contrary to what docs suggest, the
          # latter causes problems for terraform.
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          cml-runner \
          --cloud gcp \
          --cloud-region europe-west1-b	 \
          --cloud-type=n1-standard-1 \
          --labels=cml-runner
          
  model-training:
    needs: deploy-runner
    runs-on: [self-hosted, cml-runner]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my dummy model'
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Training a super awesome model"
          sleep 5
          echo "Training complete"
```

Hope there's a way to ensure the same auto-shutdown behavior on GCP. As it is, the risk of getting smacked with an expensive bill for an idle GPU is just too real =p

### LINKED ISSUE #662: Single accepts only one job but does not cleanup
And strangely appears as offline.

image

### PR DESCRIPTION
**Pull request by DavidGOrtega**
- Introduces waitCompletedPipelineJobs a function that waits for expected completed jobs. fixes #649 
  - Adds proc on exit event. fixes #662. closes #407 
  - After testing. closes #661 
  - SpotNotifier. Closes #650

### CODE REVIEW

File: bin/cml-runner.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ const { homedir } = require('os');
 
 const fs = require('fs').promises;
 const yargs = require('yargs');
+const { SpotNotifier } = require('ec2-spot-notification');
```
Comment (0x2b3bfa0) [inline bin/cml-runner.js:8]: Can we separate this functionality and move it to the AMI on the terraform-provider-iterative repository? While this is a must have, keeping it as part of the CML code would introduce another unrelated responsibility to this codebase.

Comment (0x2b3bfa0) [reply bin/cml-runner.js:8]: We can just `curl` the `169.254.169.254` endpoint in a loop and run `systemctl stop cml` once we get a termination notice, all from the instance script.

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: Lets open another ticket and use for now the already done work that also works.

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: Also, we might just want this behaviour with the runner, so I guess it should go in the TPI runner resource at most

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: > Can we separate this functionality and move it to the AMI and fallback on the terraform-provider-iterative repository? While this is a must have, keeping it as part of the CML code would introduce another unrelated responsibility to this codebase.

Actually I disagree, Its a part of the logic that we are setting to handle long job runners. The same that we do with the 72 hours in example. And ensures the integrty and responsability of the runner

Comment (0x2b3bfa0) [reply bin/cml-runner.js:8]: > _Also, we might just want this behaviour with the runner, so I guess it should go in the TPI runner resource at most_

Agreed!

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: Putting it outside makes more difficult to follow up the logic that ensures this feature of the runner. It MUST be definitely inside the runner

Comment (0x2b3bfa0) [reply bin/cml-runner.js:8]: > _Actually I disagree, Its a part of the logic that we are setting to handle long job runners. The same that we do with the 72 hours in example. And ensures the integrty and responsability of the runner_

I also disagree in turn. 😈  This is a cloud-specific termination detection mechanism and, no matter what its purpose is, should ideally be handled at the `resource_cml_runner` level at most. This project should not care about clouds but only about SCM platforms, and use `SIGTERM` as a common signal for every termination scenario.

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: > should ideally be handled at the resource_cml_runner level at most. This project should not care about clouds but only about SCM platforms, and use SIGTERM as a common signal for every termination scenario.

Why? why SCMs and not clouds? Who puts those constrains? Putting it outside its not a good idea. Indeed Im missing someting... whatch next commit

Comment (0x2b3bfa0) [reply bin/cml-runner.js:8]: > _Putting it outside makes more difficult to follow up the logic that ensures this feature of the runner. It MUST be definitely inside the runner_

More than a "feature" of the runner, I would consider it a cloud-vendor-specific patch to notify processes on spot termination with the same mechanism used for instance termination.

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: I think that the latest commit closes the discussion

Comment (0x2b3bfa0) [reply bin/cml-runner.js:8]: You're making the AWS spot instance termination detection logic optional, but...

1. How are we detecting the termination of Azure spot and Google Compute preemptive instances?
2. Do you still think that it's a good idea to introduce code specific to cloud vendors in the CML repository?

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: > Do you still think that it's a good idea to introduce code specific to cloud vendors in the CML repository?

yes, I would like to have all the base code together. If it were for me the TPI would be done in js... actually... I have a proposal 😉 

> How are we detecting the termination of Azure spot and Google Compute preemptive instances?

It does not exists. SIGTERM should suffice. Actually in AWS is intermittent. Seems that SIGTERM does not always work. ideally we should not need it.

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: Anyway if the code works correctly and the direction is not clear is better to release and USE already developed and tested code

Comment (0x2b3bfa0) [reply bin/cml-runner.js:8]: > _yes, I would like to have all the base code together. If it were for me the TPI would be done in js... actually... I have a proposal_

I would too, if Hashicorp had chosen to implement Terrraform in JavaScript. Given that it's not the case, I'd prefer to separate the responsibilities where they make most sense, keeping all the cloud-specific logic in the provider and all the SCM-specific logic in CML, as we do now.

> _It does not exists. SIGTERM should suffice. Actually in AWS is intermittent. Seems that SIGTERM does not always work. ideally we should not need it._

Then, shouldn't this be a patch on the provider so we convert AWS termination notifications to a normal `SIGTERM` signal? If you can't tell the difference between spot termination and instance terminaltion in other vendors, why do it differently on this one?

File: src/drivers/github.js [hunk 2]
```diff
@@ -258,7 +258,8 @@ class Github {
       name,
       labels: labels.map(({ name }) => name),
       online: status === 'online',
-      busy
+      busy,
+      status
```
Comment (0x2b3bfa0) [inline src/drivers/github.js:262]: Why is this needed?

File: src/drivers/gitlab.js [hunk 3]
```diff
@@ -176,14 +176,15 @@ class Gitlab {
...
         labels: (
           await this.request({ endpoint: `/runners/${id}`, method: 'GET' })
         ).tag_list,
         online,
-        busy: active && online
+        busy: active && online,
+        status
       }))
     );
   }
```
Comment (0x2b3bfa0) [inline src/drivers/gitlab.js:190]: Why is this needed? Same as https://github.com/iterative/cml/pull/653/files#r673025416

File: bin/cml-runner.js (hunk 1 above)
Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: > I would too, if Hashicorp had chosen to implement Terrraform in JavaScript. Given that it's not the case,

Im thinking to do all in JS executed with V8. At the very end we are using the vendors SDK that already exists in JS

> Then, shouldn't this be a patch on the provider so we convert AWS termination notifications to a normal SIGTERM signal? If you can't tell the difference between spot termination and instance terminaltion in other vendors, why do it differently on this one?

Reasons: 

 - More complex in the TPI
 - More obscure having another service or whatever...
 - This runner could be launched manually inside an AWS instance and still works on its own

File: src/drivers/github.js (hunk 2 above)
Comment (DavidGOrtega) [reply src/drivers/github.js:262]: We were doing it before, we need to check the status of completion

File: src/drivers/gitlab.js (hunk 3 above)
Comment (DavidGOrtega) [reply src/drivers/gitlab.js:190]: To be consistent with something that we were doing

Comment (0x2b3bfa0) [reply src/drivers/gitlab.js:190]: Let's move the conversation to https://github.com/iterative/cml/pull/653/files#r673025416

File: src/drivers/github.js (hunk 2 above)
Comment (0x2b3bfa0) [reply src/drivers/github.js:262]: Where are we using the value of this property in the code? 🤔

Comment (0x2b3bfa0) [reply src/drivers/github.js:262]: And, what's the relationship between the `status` returned by this function and the completion of a job?

Comment (DavidGOrtega) [reply src/drivers/github.js:262]:
```js
.filter((job) => job.status === 'completed')
```

Comment (DavidGOrtega) [reply src/drivers/github.js:262]: Its true. I added it to check the runner status with the first solution

Comment (0x2b3bfa0) [reply src/drivers/github.js:262]: That `filter` is taking the output from `cml.pipelineJobs` and not `cml.runners` unless I missed something. 🤔

Comment (DavidGOrtega) [reply src/drivers/github.js:262]: Anyway is a nice field

Comment (DavidGOrtega) [reply src/drivers/github.js:262]: > That filter is taking the output from cml.pipelineJobs and not cml.runners unless I missed something. 🤔

Yes,I remembered the first approach that were runners indeed

Comment (0x2b3bfa0) [reply src/drivers/github.js:262]: I'm no expert in measuring the niceness of fields, but it has been superseded by `online` and `busy` fields, that offer the same values across all the supported platforms.

File: src/drivers/gitlab.js [hunk 4]
```diff
@@ -176,14 +176,15 @@ class Gitlab {
...
+      runners.map(async ({ id, description, active, online, status }) => ({
         id,
         name: description,
         labels: (
           await this.request({ endpoint: `/runners/${id}`, method: 'GET' })
         ).tag_list,
         online,
-        busy: active && online
+        busy: active && online,
+        status
```
Comment (0x2b3bfa0) [inline src/drivers/gitlab.js:187]:
```suggestion
        busy: active && online
```

File: src/drivers/github.js (hunk 2 above)
Comment (DavidGOrtega) [reply src/drivers/github.js:262]: It might not be enough actually. And i would say that I would deprecate online and busy in favour of status which is richer and something that we are exposing for the viewer

Comment (0x2b3bfa0) [reply src/drivers/github.js:262]: The `status` field doesn't offer the same values across platforms, while `online` and `busy` do. Nevertheless, we should consider this separately; the `status` field is not necessary for this pull request.

File: src/drivers/gitlab.js [hunk 5]
```diff
@@ -176,14 +176,15 @@ class Gitlab {
     const endpoint = `/runners?per_page=100`;
     const runners = await this.request({ endpoint, method: 'GET' });
     return await Promise.all(
-      runners.map(async ({ id, name, description, active, online }) => ({
+      runners.map(async ({ id, description, active, online, status }) => ({
```
Comment (0x2b3bfa0) [inline src/drivers/gitlab.js:179]:
```suggestion
      runners.map(async ({ id, description, active, online }) => ({
```
See [this conversation](https://github.com/iterative/cml/pull/653/files/fe8831ad8674554d0081ebfba0d83e4f24bf7f75#r673025416) for context.

File: src/drivers/github.js (hunk 2 above)
Comment (0x2b3bfa0) [reply src/drivers/github.js:262]:
```suggestion
```

File: bin/cml-runner.js [hunk 6]
```diff
@@ -234,12 +235,34 @@ const runLocal = async (opts) => {
...
+        return new Promise((resolve, reject) => {
+          try {
+            if (RUNNER_JOBS_RUNNING.length === 1) {
+              resolve([RUNNER_JOBS_RUNNING[0].id]);
+              return;
+            }
+
+            const watcher = setInterval(async () => {
+              const jobs = (
+                await cml.pipelineJobs({ jobs: RUNNER_JOBS_RUNNING })
```
Comment (0x2b3bfa0) [inline bin/cml-runner.js:248]: The GitLab driver does not have `pipelineJobs` 🤔

Comment (DavidGOrtega) [reply bin/cml-runner.js:248]: Its not needed for it

Comment (0x2b3bfa0) [reply bin/cml-runner.js:248]: After https://github.com/iterative/cml/pull/653/commits/082fcba905e2708de9d013af9a222e6fc2a98438 it won't throw a TypeError when calling an undefined function. Still, I suspect that it's going to throw the `not implemented` error you introduce.

Should we call `waitCompletedPipelineJobs` only if `driver === 'github'` or something?

Comment (DavidGOrtega) [reply bin/cml-runner.js:248]: No, actually that will never be called in Gitlab. We maintain it to give coherence and to establish the interface. n Gitalb that will never ever be called

Comment (DavidGOrtega) [reply bin/cml-runner.js:248]: Let me clarify. In Gitlab the logs comes with the jobID thing that does not happen in Github and we have to gather the jobs to check the completion of the id we knew

Comment (0x2b3bfa0) [reply bin/cml-runner.js:248]: > _No, actually that will never be called in Gitlab_ <sup>[citation needed]</sup>

Is there any guard code to prevent that? 🤔

Comment (DavidGOrtega) [reply bin/cml-runner.js:248]: > Is there any guard code to prevent that? 🤔

the existance of the job.id

Comment (DavidGOrtega) [reply bin/cml-runner.js:248]:
```js
const jobs = job ? [job] : await waitCompletedPipelineJobs();
```

Comment (DavidGOrtega) [reply bin/cml-runner.js:248]: As  say in GL that id is known always in the log

Comment (0x2b3bfa0) [reply bin/cml-runner.js:248]: 👌🏼  Thanks!

File: bin/cml-runner.js (hunk 1 above)
Comment (0x2b3bfa0) [reply bin/cml-runner.js:8]: > _Im thinking to do all in JS executed with V8. At the very end we are using the vendors SDK that already exists in JS_

Not sure about the specific advantages of V8 over any other engine for this use case, but anyhow. This is a completely separate discussion topic.

> * More complex in the TPI

Not _that_ complex.

> * More obscure having another service or whatever...

Not as obscure as moving cloud-specific code to the CML repository instead of abstracting over signals, in my opinion.

> * This runner could be launched manually inside an AWS instance and still works on its own

Do we _really_ want to support this use case? What's the advantage of supporting it if we don't do the same for the other providers?

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: All advantages despite that you disagree.

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: > Not as obscure as moving cloud-specific code to the CML repository

CML repository is a runner also that can check whatever is needed to ensure the feature it offers. Transparent spot instances

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: > Not that complex.

We have to check also the noRetry... pass it.. create another service or whatever, business logic broken in multiple parts ... Ugly! 
I can't believe that you can not see the benefit

Comment (DavidGOrtega) [reply bin/cml-runner.js:8]: > Not sure about the specific advantages of V8 over any other engine for this use case, but anyhow. This is a completely separate discussion topic.

Im telling you a solution to avoid Golang source code that Im planning to also unify the base source code that we were discussing

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 are you approving it? We have several p0s that are fixed here. I want to release it ASAP

**Comment by 0x2b3bfa0** [comment]
I'm hesitant to approve the inclusion of SpotNotifier in the CML code base, especially without a follow-up technical debt / discussion issue.

I'm going to run tests on Google Cloud to confirm that #661 gets fixed and check everything for approval, but I'd prefer to discuss this in the weekly meeting so we can take better decisions.

**Comment by DavidGOrtega** [comment]
> I'm hesitant to approve the inclusion of SpotNotifier in the CML code base, especially without a follow-up technical debt / discussion issue.

Open a ticket to follow up. I do agree with it and I wont agree the opposite, so... To me there is not technical debt here

> I'm going to run tests on Google Cloud to confirm that #661 gets fixed and check everything for approval, but I'd prefer to discuss this in the weekly meeting so we can take better decisions.

I have tested it. The machines are disposed

**Comment by DavidGOrtega** [comment]
opens #663

**Review by 0x2b3bfa0 — APPROVED** [review]
Looks good to me, except for the inclusion of SpotNotifier. Approving just because of https://github.com/iterative/cml/pull/653#issuecomment-883373907 to avoid blocking priority 0 fixes.

**Comment by ivyleavedtoadflax** [comment]
@DavidGOrtega @0x2b3bfa0 thanks so much for this!

**Comment by lemontheme** [comment]
Reporter of #661 checking in. Indeed, thanks for jumping on this!

Unnnnnfortunately, I'm afraid that I'm still seeing the same behavior as before. (I'm assuming that the iterative/setup-cml@v1 action uses the latest cml release.) In 5 out of 5 separate runs, my Google CE instances stayed alive rather than being shutdown.

Seeing as your tests passed though, maybe it's user error on my end?

**Comment by DavidGOrtega** [comment]
@lemontheme I would need to see your workflow. Tests with TPI indicates that the instances are disposed after the expected time.

**Comment by lemontheme** [comment]
@DavidGOrtega sorry for the late reply. I tested with the same workflow as in #661

**Comment by 0x2b3bfa0** [comment]
@lemontheme, can you please open a new issue?
