### PR TITLE
Bullet proof runner termination

### LINKED ISSUE #690: Idle CML runners are not being killed after possible errors
We had two CML runners not terminate correctly yesterday, and stayed up overnight. Both had errors with the runner stage - one is screenshotted here, the other however was just due to a syntax error in a DVC command.

image

### LINKED ISSUE #808: `cml runner` early shutdown from idle-timeout with active job
Cloud provider: `gcp`
SCM / CICD: `github` / `actions`

I have been playing with short `--idle-timeout` values and I was a bit baffled when I encountered this. One workflow shutdown earlier before the GitHub action completes the final job, and the other completes as expected, but they are using nearly identical workflows.

Successful workflow:
```yml
name: Build and run Inference - DEV
on:
  push:
    branches: [dev]
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/gcr-build-push@main
        with:
          tags: latest
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          GCR-key: ${{ secrets.GCP_GCR_KEY }}
          container-name: ***
  deploy-runner:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GCP_CML_RUNNER_KEY }}
        run: |
          cml-runner \
            --single \
            --idle-timeout=360 \
            --token=${{ secrets.PAT_DCB }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-standard-16
  run-inference:
    needs: [build, deploy-runner]
    runs-on: [self-hosted, cml]
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - name: Setup Container image name
        run: echo "ML_CONTAINER=gcr.io/${{ secrets.GCP_PROJECT_ID }}/***" >> "${GITHUB_ENV}"
      - name: Docker GCR Login
        uses: docker/login-action@v1
        with: 
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_GCR_KEY }}
      - name: Load container from GCR
        run: docker pull ${{ env.ML_CONTAINER }}:latest
      - name: Run Inference
        run: |
          docker run ****
```
Failed workflow:
```yml
name: Build and run Inference - PROD
on:
  schedule: # Saturday at 1400 UTC
    - cron: '0 14 * * 6'
  push:
    branches: [prod]
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: dacbd/gcr-build-push@v1
        with:
          tags: latest
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          GCR-key: ${{ secrets.GCP_GCR_KEY }}
          container-name: ***
  deploy-runner:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Deploy runner on GCP
        env:
          GOOGLE_APPLICATION_CREDENTIALS_DATA: ${{ secrets.GCP_CML_RUNNER_KEY }}
        run: |
          cml-runner \
            --single \
            --idle-timeout=360 \
            --token=${{ secrets.PAT_DCB }} \
            --cloud=gcp \
            --cloud-region=us-west \
            --cloud-type=e2-standard-16
  run-inference:
    needs: [build, deploy-runner]
    runs-on: [self-hosted, cml]
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Setup Container image name
        run: echo "ML_CONTAINER=gcr.io/${{ secrets.GCP_PROJECT_ID }}/***" >> "${GITHUB_ENV}"
      - name: Docker GCR Login
        uses: docker/login-action@v1
        with: 
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_GCR_KEY }}
      - name: Load container from GCR
        run: docker pull ${{ env.ML_CONTAINER }}
      - name: Run Inference
        run: |
          docker run ***
```

-----------------------

Successful `cml.service` log
```
daniel_barnes@cml-z53bz3oz1t:~$ sudo journalctl -u cml.service -f
-- Logs begin at Tue 2021-11-09 20:03:04 UTC. --
Nov 09 20:05:47 cml-z53bz3oz1t systemd[1]: Started cml.service.
Nov 09 20:05:52 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"Preparing workdir /tmp/tmp.7PolL2jgVJ/.cml/cml-z53bz3oz1t..."}
Nov 09 20:05:52 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"Launching github runner"}
Nov 09 20:06:02 cml-z53bz3oz1t cml.sh[17039]: {"level":"warn","message":"SpotNotifier can not be started."}
Nov 09 20:06:03 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:03.618Z","level":"info","message":"runner status","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:06:03 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:03.619Z","level":"info","message":"runner status √ Connected to GitHub","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:06:04 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:04.057Z","level":"info","message":"runner status Listening for Jobs","repo":"https://github.com/yyyy/xxxx","status":"ready"}
Nov 09 20:06:16 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:06:15.944Z","job":4157205540,"level":"info","message":"runner status Running job: run-inference","repo":"https://github.com/yyyy/xxxx","status":"job_started"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:18:21.355Z","job":"","level":"info","message":"runner status Job run-inference completed with result: Succeeded","repo":"https://github.com/yyyy/xxxx","status":"job_ended","success":true}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:18:21.595Z","level":"info","message":"runner status √ Removed .credentials","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"date":"2021-11-09T20:18:21.596Z","level":"info","message":"runner status √ Removed .runner","repo":"https://github.com/yyyy/xxxx"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"runner status","reason":"proc_exit","status":"terminated"}
Nov 09 20:18:21 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"waiting 20 seconds before exiting..."}
Nov 09 20:18:41 cml-z53bz3oz1t cml.sh[17039]: {"level":"info","message":"Unregistering runner cml-z53bz3oz1t..."}
Nov 09 20:18:41 cml-z53bz3oz1t cml.sh[17039]: {"level":"error","message":"\tFailed: Cannot destructure property 'id' of '(intermediate value)' as it is undefined."}
Nov 09 20:18:44 cml-z53bz3oz1t systemd[1]: cml.service: Succeeded.
```

Failed `cml.service` log
```
daniel_barnes@cml-uawryesbyo:~$ sudo journalctl -u cml.service -f
-- Logs begin at Tue 2021-11-09 19:23:49 UTC. --
Nov 09 19:26:34 cml-uawryesbyo systemd[1]: Started cml.service.
Nov 09 19:26:39 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"Preparing workdir /tmp/tmp.TAz3gTOugR/.cml/cml-uawryesbyo..."}
Nov 09 19:26:39 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"Launching github runner"}
Nov 09 19:26:49 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"SpotNotifier can not be started."}
Nov 09 19:26:50 cml-uawryesbyo cml.sh[17135]: {"date":"2021-11-09T19:26:50.163Z","level":"info","message":"runner status","repo":"https://github.com/yyyy/xxxx"}
Nov 09 19:26:50 cml-uawryesbyo cml.sh[17135]: {"date":"2021-11-09T19:26:50.163Z","level":"info","message":"runner status √ Connected to GitHub","repo":"https://github.com/yyyy/xxxx"}
Nov 09 19:26:50 cml-uawryesbyo cml.sh[17135]: {"date":"2021-11-09T19:26:50.583Z","level":"info","message":"runner status Listening for Jobs","repo":"https://github.com/yyyy/xxxx","status":"ready"}
Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Failed parsing log: Reduce of empty array with no initial value"}
Nov 09 19:27:02 cml-uawryesbyo cml.sh[17135]: {"level":"warn","message":"Original log bytes, as Base64: 2021-11-09 19:27:01Z: Running job: run-inference\n"}
Nov 09 19:32:51 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"runner status","reason":"timeout:360","status":"terminated"}
Nov 09 19:32:51 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"waiting 20 seconds before exiting..."}
Nov 09 19:33:11 cml-uawryesbyo cml.sh[17135]: {"level":"info","message":"Unregistering runner cml-uawryesbyo..."}
Nov 09 19:33:12 cml-uawryesbyo cml.sh[17135]: {"level":"error","message":"\tFailed: Bad request - Runner \"cml-uawryesbyo\" is still running a job\""}
Nov 09 19:33:22 cml-uawryesbyo systemd[1]: cml.service: Succeeded.
```

### PR DESCRIPTION
**Pull request by DavidGOrtega**
In GH sometimes the log for a new job or job termination does not fails ending up in two scenarios:
 - a runner that runs forever because it believes that it has a job in the pipeline
 - a runner that terminates prematurely because it does not detect the new job

This attempt 
 - For GH checks the runner `busy` status to determine if the runner is still busy or not despite the registered job. If busy tries another round if idle time. If not but it has jobs in the pipeline restarts the jobs and gives another shot.
 - Removes the chrono in favour of just using the setTimeout with the idle time.
 - Simplifies the job queue logic
 - Listens only for exit runner process
 - DRYes the code a bit
 - Smaller destroy window to allow spot instances to terminate properly
 - closes #690 
 - closes #808

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
Rebased over #703, courtesy of the Weekly Release Manager™

**Comment by ivyleavedtoadflax** [comment]
Hi! Any news on if/when this will get merged? :pray:

**Comment by casperdcl** [comment]
Hopefully within a month :)

**Comment by DavidGOrtega** [comment]
> Hi! Any news on if/when this will get merged? 🙏

Hi @ivyleavedtoadflax the reason why has not been merged yet is because we already merged two PR that should have fixed any GCP issue. 
I will come back to review this this week as I know that you are affected in GCP

**Comment by DavidGOrtega** [comment]
Im pretty happy with this version.
I have done many testing within a reasonable human effort during these days.
Removing the net, killing the runner...
This is the log of my last human acceptance test... I wonder how we could automate this...

```
info: Preparing workdir /home/runner...
info: Launching github runner
info: runner status {"date":"2022-02-28T21:49:40.640Z","repo":"https://github.com/DavidGOrtega/fashion_mnist"}
info: runner status √ Connected to GitHub {"date":"2022-02-28T21:49:40.641Z","repo":"https://github.com/DavidGOrtega/fashion_mnist"}
info: runner status Current runner version: '2.288.1' {"date":"2022-02-28T21:49:41.521Z","repo":"https://github.com/DavidGOrtega/fashion_mnist"}
info: runner status Listening for Jobs {"date":"2022-02-28T21:49:41.527Z","repo":"https://github.com/DavidGOrtega/fashion_mnist","status":"ready"}
warn: SpotNotifier can not be started.
info: runner status Running job: train {"date":"2022-02-28T21:49:57.302Z","job":"gh","repo":"https://github.com/DavidGOrtega/fashion_mnist","status":"job_started"}
error: Runner should be idle. Reseting jobs. Will try again in 20 secs
error: Error connecting the SCM. Will try again in 20 secs
error: Error connecting the SCM. Will try again in 20 secs
error: Runner seems to be busy yet. Will try again in 20 secs
error: Runner seems to be busy yet. Will try again in 20 secs
error: Runner seems to be busy yet. Will try again in 20 secs
error: Runner seems to be busy yet. Will try again in 20 secs
error: Runner seems to be busy yet. Will try again in 20 secs
error: Runner seems to be busy yet. Will try again in 20 secs
error: Runner seems to be busy yet. Will try again in 20 secs
info: runner status Job train completed with result: Succeeded {"date":"2022-02-28T21:53:05.350Z","job":"gh","repo":"https://github.com/DavidGOrtega/fashion_mnist","status":"job_ended","success":true}
info: runner status {"reason":"timeout:20","status":"terminated"}
info: waiting 10 seconds before exiting...
info: Unregistering runner cml-s1i6nvs6dl...
info:   Success
```

File: src/drivers/github.js [hunk 1]
```diff
@@ -260,6 +260,7 @@ class Github {
         const url = `https://github.com/actions/runner/releases/download/${ver}/actions-runner-${arch}-${ver.substring(
           1
         )}.tar.gz`;
+        console.log(url);
```
Comment (dacbd) [inline src/drivers/github.js:263]: `winston` or miss one?

**Comment by dacbd** [comment]
> I wonder how we could automate this...

That's always the fun part isn't it 😈

**Comment by DavidGOrtega** [comment]
I have left skipped smoke tests due to credentials issues
I can remove them and follow up later

**Comment by DavidGOrtega** [comment]
Please review 🙏

File: src/drivers/gitlab.js [hunk 2]
```diff
@@ -221,18 +221,35 @@ class Gitlab {
...
     return await Promise.all(
-      runners.map(async ({ id, description, active, online }) => ({
+      runners.map(async ({ id, description, online }) => ({
         id,
         name: description,
         labels: (
           await this.request({ endpoint: `/runners/${id}`, method: 'GET' })
         ).tag_list,
-        online,
-        busy: active && online
```
Comment (0x2b3bfa0) [inline src/drivers/gitlab.js:231]: Doesn't `busy` condition work as intended?

File: src/cml.js [hunk 3]
```diff
@@ -235,17 +235,14 @@ class CML {
...
-        } else if (
-          data.includes('Job') &&
-          data.includes('completed with result')
-        ) {
-          log.job = '';
+        } else if (data.includes('completed with result')) {
+          log.job = id;
           log.status = 'job_ended';
-          log.success = data.includes('Succeeded');
+          log.success = data.includes('Succeded');
```
Comment (0x2b3bfa0) [inline src/cml.js:245]: Is this a typo?

File: bin/cml/runner.js [hunk 4]
```diff
@@ -229,59 +253,56 @@ const runLocal = async (opts) => {
...
-        RUNNER_JOBS_RUNNING = RUNNER_JOBS_RUNNING.filter(
-          (job) => !jobs.includes(job.id)
+            idle = false;
+          }
+        }
+      } catch (err) {
+        winston.error(
+          `Error connecting the SCM. Will try again in ${idleTimeout} secs`
         );
+
```
Comment (0x2b3bfa0) [inline bin/cml/runner.js:296]:
```suggestion
        err.message = 'Failed connecting with the SCM; will try again in ${idleTimeout} seconds: ' + err.message;
        winston.error(err);
```

Same as above. Also, why use `--idle-timeout` value for retries? 🤔

File: bin/cml/runner.js [hunk 5]
```diff
@@ -229,59 +253,56 @@ const runLocal = async (opts) => {
...
           }
-        });
-      };
 
-      if (!RUNNER_SHUTTING_DOWN) {
-        const jobs = job ? [job] : await waitCompletedPipelineJobs();
+          if (job && idle) {
+            winston.error(
+              `Runner seems to be busy yet. Will try again in ${idleTimeout} secs`
+            );
```
Comment (0x2b3bfa0) [inline bin/cml/runner.js:287]: Same as below.

File: bin/cml/runner.js [hunk 6]
```diff
@@ -229,59 +253,56 @@ const runLocal = async (opts) => {
...
+      let idle = !RUNNER_JOBS_RUNNING.length;
+
+      try {
+        if (cml.driver === 'github') {
+          const job = await cml.runnerJob({ runnerId: RUNNER_ID });
+
+          if (!job && !idle) {
+            winston.error(
+              `Runner should be idle. Reseting jobs. Will try again in ${idleTimeout} secs`
+            );
```
Comment (0x2b3bfa0) [inline bin/cml/runner.js:279]: Should be a warning?

**Review by 0x2b3bfa0 — COMMENTED** [review]
No human can test all the edge cases you went through; at least, not with 24 hour days. Still, everything looks pretty reasonable and, indeed, it does solve several issues.

Please take a look to my review comments if you have time.

File: src/drivers/gitlab.js (hunk 2 above)
Comment (DavidGOrtega) [reply src/drivers/gitlab.js:231]: No. Indeed active is deprecated and unfortunately never meant "executing"

File: bin/cml/runner.js (hunk 6 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:279]: gave you my first 👍 👎 !!!!!
 initially thought about a warn, but indeed the nature of it is an error, recoverable but an error... not sure

Comment (0x2b3bfa0) [reply bin/cml/runner.js:279]: I see you're developing a taste for my creative 👍🏼 👎🏼 “yes and no” neutral reaction. 😄 I think the same: as long as it's consistent, it's just a matter of style.

File: bin/cml/runner.js (hunk 4 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:296]: we have simplified the timer logic. We use the idle-timeout to set the cleanup timer

Comment (0x2b3bfa0) [reply bin/cml/runner.js:296]: [L304](https://github.com/iterative/cml/pull/689/files#diff-10fb1f5fadda740e153419ffc626eda08260bf2f3b7ba973facefc001d9dcec9R304)? Sounds like an overload of `--idle-timeout` but makes sense.

Comment (DavidGOrtega) [reply bin/cml/runner.js:296]: > [L304](https://github.com/iterative/cml/pull/689/files#diff-10fb1f5fadda740e153419ffc626eda08260bf2f3b7ba973facefc001d9dcec9R304)? Sounds like an overload of `--idle-timeout` but makes sense.

Yes. We just only need to run the cleanup at `--idle-timeout` seconds. What we are saying in the logs is that we will retry in the next cleanup.

File: src/cml.js (hunk 3 above)
Comment (DavidGOrtega) [reply src/cml.js:245]: And this? 😁 
```json
"status": {
                "running": 0,
                "succeeded": 1
              },
```

Comment (0x2b3bfa0) [reply src/cml.js:245]: According to [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/succeed?q=succeeded) and [Kubernetes](https://kubernetes.io/docs/concepts/workloads/controllers/job), `succeeded` is not a typo, if that's what you mean. 🙃

Comment (DavidGOrtega) [reply src/cml.js:245]: succeded is not a typo. GH uses it

Comment (DavidGOrtega) [reply src/cml.js:245]: https://en.wiktionary.org/wiki/succeded

Comment (0x2b3bfa0) [reply src/cml.js:245]: ### [Wiktionary → succeded](https://en.wiktionary.org/wiki/succeded)
> Verb — **succeded**
> _simple past tense and past participle of [succede](https://en.wiktionary.org/wiki/succede)_
### [Wiktionary → succede](https://en.wiktionary.org/wiki/succede)
> Verb — **succede** (third-person singular simple present [succedes](https://en.wiktionary.org/wiki/succedes#English), present participle [succeding](https://en.wiktionary.org/wiki/succeding#English), simple past and past participle [succeded](https://en.wiktionary.org/wiki/succeded#English))
> 👉🏼 Dated👈🏼  form of [succeed](https://en.wiktionary.org/wiki/succeed#English)

Comment (DavidGOrtega) [reply src/cml.js:245]: It is Succeeded indeed in GH... 🤦

Comment (0x2b3bfa0) [reply src/cml.js:245]: > _GH uses it_

```console
$ git clone --branch v2.288.1 https://github.com/actions/runner
$ grep --recursive --ignore-case succeded runner || echo not true
$ grep --recursive --ignore-case succeeded runner && echo not true
```

```console
2022-03-07 14:42:56Z: Listening for Jobs
2022-03-07 14:43:52Z: Running job: test
2022-03-07 14:44:00Z: Job test completed with result: Succeeded
```

https://github.com/actions/runner/blob/ad0d0c4d0a9e58943a688f66586b4dadf524ad9f/src/Runner.Listener/JobDispatcher.cs#L534
term.WriteLine($"{DateTime.UtcNow:u}: Job {message.JobDisplayName} completed with result: {result}");

https://github.com/actions/runner/blob/ad0d0c4d0a9e58943a688f66586b4dadf524ad9f/src/Runner.Common/Util/TaskResultUtil.cs#L21-L32
        public static TaskResult TranslateFromReturnCode(int returnCode)
        {
            int resultInt = returnCode - _returnCodeOffset;
            if (Enum.IsDefined(typeof(TaskResult), resultInt))
            {
                return (TaskResult)resultInt;
            }
            else
            {
                return TaskResult.Failed;
            }
        }


https://github.com/actions/runner/blob/be9632302ceef50bfb36ea998cea9c94c75e5d4d/src/Sdk/DTWebApi/WebApi/TaskResult.cs#L6-L25

Comment (0x2b3bfa0) [reply src/cml.js:245]: > _It is Succeeded indeed in GH..._

Whoops! Sorry, I missed your comment. Yes, it's `succeeded` and we should probably update our code accordingly.

File: src/cml.test.js [hunk 7]
```diff
@@ -196,4 +218,30 @@ describe('Gitlab tests', () => {
...
+    });
+    expect(log.status).toBe('job_ended');
+    expect(log.success).toBe(true);
+
+    log = cml.parseRunnerLog({
+      data: '{"duration_s":120.0120526,"job":1396213069,"level":"warning","msg":"Job failed: execution took longer than 2m0s seconds","project":27856642,"runner":"2SGFrnGt","time":"2021-07-02T16:47:47Z"}'
+    });
+    expect(log.status).toBe('job_ended');
+    expect(log.success).toBe(false);
+  });
```
Comment (0x2b3bfa0) [inline src/cml.test.js:246]: Would it be useful to add some similar for GitHub, so we know if our tests (cough) _succeed_ or not on all the supported platforms?

File: src/cml.test.js [hunk 8]
```diff
@@ -75,6 +75,28 @@ describe('Github tests', () => {
...
+  test('Runner logs', async () => {
+    const cml = new CML();
+    cml.driver = 'github';
+    let log = cml.parseRunnerLog({ data: 'Listening for Jobs' });
+    expect(log.status).toBe('ready');
+
+    log = cml.parseRunnerLog({ data: 'Running job' });
+    expect(log.status).toBe('job_started');
+
+    log = cml.parseRunnerLog({ data: 'completed with result: Succeded' });
```
Comment (0x2b3bfa0) [inline src/cml.test.js:88]:
```suggestion
    log = cml.parseRunnerLog({ data: 'completed with result: Succeeded' });
```

See [above](https://github.com/iterative/cml/pull/689/files#r820782354)

File: bin/cml/runner.js [hunk 9]
```diff
@@ -47,12 +47,19 @@ const shutdown = async (opts) => {
...
-            async (job) => await cml.pipelineRestart({ jobId: job.id })
-          )
-        );
+      if (!noRetry) {
+        if (cml.driver === 'github') {
+          const job = await cml.runnerJob({ runnerId: RUNNER_ID });
+          if (job) RUNNER_JOBS_RUNNING = [job];
+        }
+
+        if (RUNNER_JOBS_RUNNING.length) {
```
Comment (dacbd) [inline bin/cml/runner.js:56]: I take it you guys are okay with this style of truthy-ness? On a broader scope, do you reference anything in particular for js/node style guide?

File: package.json [hunk 10]
```diff
@@ -78,6 +78,8 @@
     "fs-extra": "^9.1.0",
     "git-url-parse": "^11.6.0",
     "globby": "^11.0.4",
+    "https-proxy-agent": "^5.0.0",
+    "is-ip": "^3.1.0",
```
Comment (dacbd) [inline package.json:82]: Should this be a dev dependency since it's only used in the tests?

File: src/cml.js [hunk 11]
```diff
@@ -261,12 +258,9 @@ class CML {
...
         if (msg.endsWith('received')) {
           log.status = 'job_started';
-        } else if (
-          msg.startsWith('Job failed') ||
-          msg.startsWith('Job succeeded')
-        ) {
+        } else if (msg.includes('completed with result')) {
           log.status = 'job_ended';
-          log.success = !msg.startsWith('Job failed');
+          log.success = !msg.includes('Succeded');
```
Comment (dacbd) [inline src/cml.js:263]:
```suggestion
          log.success = !msg.includes('Succeeded');
```

File: bin/cml/runner.js (hunk 9 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:56]: @dacbd I do not follow you 🙂 could you please elaborate a bit more?

File: package.json (hunk 10 above)
Comment (DavidGOrtega) [reply package.json:82]: is_ip at most and its not a big deal, https-proxy-agent is to deal with http proxies

Comment (dacbd) [reply package.json:82]: `is_ip` was the one I was referring to, simply limiting to a dev dependency. I agree it's "not a big deal" since it is indeed very simple. But why package code that will never run?

Comment (DavidGOrtega) [reply package.json:82]: `setup-cml` uses npm install like we do in the distros. We are not adding the --prod flag.
Probably we should do it.

File: bin/cml/runner.js (hunk 9 above)
Comment (dacbd) [reply bin/cml/runner.js:56]: Sure, being more explicit in the condition `if (RUNNER_JOBS_RUNNING.length)` the logical question is "Are there jobs in the array?" I suppose my question is, is there an organizational style guide on truthy js values. 
```
console.log(
  -1 ? "true" : "false",
  0 ? "true" : "false",
  1 ? "true" : "false"
)
```

Comment (DavidGOrtega) [reply bin/cml/runner.js:56]: > is there an organizational style guide on truthy js values

organizational at Iterative? We have an eslint in place . We could have done explicit comparison but JS behaves equally with one additional benefit: array.length is fastest in speed (and shorter in writing) than array.length > 0 

```js
if (RUNNER_JOBS_RUNNING.length > 0)
```

What is the point? Are you interested in learning out JS style? 🙂

Comment (0x2b3bfa0) [reply bin/cml/runner.js:56]: > _I take it you guys are okay with this style of truthy-ness?_

Technically speaking, yes, “<i><a href="https://262.ecma-international.org/5.1/#sec-15.4">every Array object has a length property whose value is always a <b>nonnegative</b> integer less than 2<sup>32</sup></a></i>”

> _On a broader scope, do you reference anything in particular for js/node style guide?_

Supposedly (#596), we follow the [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript), but the conditional you've spotted is a documented antipattern:

> _[15.3 Use shortcuts for booleans, but explicit comparisons for strings and numbers.](https://github.com/airbnb/javascript#comparison--shortcuts)_
>
> ```javascript
> // bad
> if (collection.length) {
>   // ...
> }
> 
> // good
> if (collection.length > 0) {
>   // ...
> }
> ```

Comment (DavidGOrtega) [reply bin/cml/runner.js:56]: > Supposedly (https://github.com/iterative/cml/issues/596)

Its still open. We never stick to it yet aside having the original Iterative linter. As far as I remember

Comment (0x2b3bfa0) [reply bin/cml/runner.js:56]: https://cml.dev/doc/contributing/core#submitting-contributions
> _All JS code should follow the [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript)._

Comment (DavidGOrtega) [reply bin/cml/runner.js:56]: > should

should is the keyword here

Comment (casperdcl) [reply bin/cml/runner.js:56]:
```py
# best
if collection:
    print("the zen of Python")
```

Comment (DavidGOrtega) [reply bin/cml/runner.js:56]: Maybe I have found the why we are delayed 😁

Comment (DavidGOrtega) [reply bin/cml/runner.js]: I have fix it to not have to debate philosophically during the next 2 hours 😁

File: bin/cml/runner.js [hunk 12]
```diff
@@ -229,59 +253,56 @@ const runLocal = async (opts) => {
...
+    const watcher = setInterval(async () => {
+      let idle = RUNNER_JOBS_RUNNING.length === 0;
+
+      try {
+        if (cml.driver === 'github') {
+          const job = await cml.runnerJob({ runnerId: RUNNER_ID });
+
+          if (!job && !idle) {
+            winston.error(
+              `Runner should be idle. Reseting jobs. Will try again in ${idleTimeout} secs`
```
Comment (casperdcl) [inline bin/cml/runner.js:278]:
```suggestion
              `Runner should be idle. Resetting jobs. Will try again in ${idleTimeout} secs`
```

File: bin/cml/runner.js [hunk 13]
```diff
@@ -229,59 +253,56 @@ const runLocal = async (opts) => {
...
+            RUNNER_JOBS_RUNNING = [];
           }
-        });
-      };
 
-      if (!RUNNER_SHUTTING_DOWN) {
-        const jobs = job ? [job] : await waitCompletedPipelineJobs();
+          if (job && idle) {
+            winston.error(
+              `Runner seems to be busy yet. Will try again in ${idleTimeout} secs`
```
Comment (casperdcl) [inline bin/cml/runner.js:286]:
```suggestion
              `Runner seems to be busy. Retrying in ${idleTimeout} secs`
```

File: bin/cml/runner.js [hunk 14]
```diff
@@ -559,7 +568,7 @@ exports.builder = (yargs) =>
       },
       destroyDelay: {
         type: 'number',
-        default: 20,
+        default: 10,
```
Comment (casperdcl) [inline bin/cml/runner.js:571]: what's the reason for this? Was 20 too much?

File: src/cml.js (hunk 3 above)
Comment (casperdcl) [reply src/cml.js]: if it helps, I hate that GH uses "Canceled" :D

File: bin/cml/runner.js (hunk 9 above)
Comment (dacbd) [reply bin/cml/runner.js]: > What is the point? Are you interested in learning our JS style? 🙂 

Yes

**Comment by DavidGOrtega** [comment]
@casperdcl @0x2b3bfa0 fixed your points 🙏

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, did you finally find https://github.com/iterative/cml/pull/689/files#r820572979 useful?

File: bin/cml/runner.js (hunk 14 above)
Comment (casperdcl) [reply bin/cml/runner.js:571]: ok but what's too little? Why not 5? Or 1? Or 0?

File: bin/cml/runner.js [hunk 15]
```diff
@@ -92,16 +99,19 @@ const shutdown = async (opts) => {
...
-  } else {
-    await unregisterRunner();
-    await retryWorkflows();
+  if (!cloud) {
+    try {
+      await unregisterRunner();
+      await retryWorkflows();
+    } catch (err) {
+      winston.error('Failed connecting with the scm');
+    }
```
[the remark this answers is not in the document]
Comment (casperdcl) [reply bin/cml/runner.js:108]: also voting to preserve `err.message`

File: bin/cml/runner.js (hunk 14 above)
Comment (0x2b3bfa0) [reply bin/cml/runner.js:571]: > _`destroyDelay` waits a bit so the provider has time to [pull logs](https://github.com/iterative/terraform-provider-iterative/blob/af2082e9f95654145adf67db660c5fac2dca0877/iterative/resource_runner.go#L240-L266) a last time if the runner fails; rationale explained on [cml#419](https://github.com/iterative/cml/pull/419). It began being [30](https://github.com/iterative/cml/blob/ef5d9b9dfa952eedf2e1ead76cd18a09b5bc86be/bin/cml-runner.js#L21) seconds and then was changed to [20](https://github.com/iterative/cml/blob/96743a4df929da6fef32161f0c09643bde998b89/bin/cml-runner.js#L20)._

File: bin/cml/runner.js [hunk 16]
```diff
@@ -559,7 +568,7 @@ exports.builder = (yargs) =>
       },
       destroyDelay: {
         type: 'number',
-        default: 20,
+        default: 10,
         hidden: true,
         description: 'Destroy delay'
```
Comment (casperdcl) [inline bin/cml/runner.js:573]:
```suggestion
        description: 'Destroy delay, leaving time to collect logs (https://github.com/iterative/cml/issues/413)'
```

File: bin/cml/runner.js (hunk 14 above)
Comment (casperdcl) [reply bin/cml/runner.js:571]: https://github.com/iterative/cml/pull/689/files#r823121962

**Comment by DavidGOrtega** [comment]
> @DavidGOrtega, did you finally find [#689 (comment)](https://github.com/iterative/cml/pull/689#discussion_r820572979) useful?

Indeed I added the error despite is not there... using templating instead of adding... not sure why is not present...

File: bin/cml/runner.js (hunk 14 above)
Comment (0x2b3bfa0) [reply bin/cml/runner.js:571]: On the provider side, see:
* [iterative/terraform-provider-iterative@`b47f801`/iterative/resource_runner.go:248](https://github.com/iterative/terraform-provider-iterative/blob/b47f8014c1a222362b43ac9c5afc8a9522fa7ea3/iterative/resource_runner.go#L248)
* [hashicorp/terraform-plugin-sdk@`9cecd71`/helper/resource/wait.go](https://github.com/hashicorp/terraform-plugin-sdk/blob/9cecd719095910f47ea6810329a18947dc6e353b/helper/resource/wait.go)
* [hashicorp/terraform-plugin-sdk@`9cecd71`/helper/resource/state.go](https://github.com/hashicorp/terraform-plugin-sdk/blob/9cecd719095910f47ea6810329a18947dc6e353b/helper/resource/state.go)
* [`resource.Retry` documentation](https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts#retry)

Terraform waits a [maximum of 10 seconds](https://github.com/hashicorp/terraform-plugin-sdk/blob/9cecd719095910f47ea6810329a18947dc6e353b/helper/resource/state.go#L196) between checks.

Comment (0x2b3bfa0) [reply bin/cml/runner.js:571]: Still, SSH connection delays and other factors may decrease the polling frequency enough to miss the logs (?)

Comment (0x2b3bfa0) [reply bin/cml/runner.js:571]: https://github.com/iterative/cml/issues/413#issuecomment-1063415985

File: bin/cml/runner.js [hunk 17]
```diff
@@ -559,9 +568,9 @@ exports.builder = (yargs) =>
       },
       destroyDelay: {
         type: 'number',
-        default: 20,
+        default: 10,
         hidden: true,
-        description: 'Destroy delay'
+        description: 'Seconds to wait for collecting logs on failure (https://github.com/iterative/cml/issues/413)'
```
Comment (DavidGOrtega) [inline bin/cml/runner.js:573]: Why do not we wait for me to fix it? I have never worked this way before.

File: bin/cml/runner.js (hunk 14 above)
Comment (0x2b3bfa0) [reply bin/cml/runner.js:571]: Documented on https://github.com/iterative/cml/issues/413#issuecomment-1063415985

File: bin/cml/runner.js (hunk 17 above)
Comment (0x2b3bfa0) [reply bin/cml/runner.js]: Whoops; sorry! Feel free to revert the commit.

File: bin/cml/runner.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply bin/cml/runner.js]: > Note: the latter should probably be a warning, and error logs should be reserved for fatal errors.

I do not agree here and we indeed agreed that it was ok

File: bin/cml/runner.js (hunk 17 above)
Comment (casperdcl) [reply bin/cml/runner.js]: 176ccf2 :)

File: bin/cml/runner.js (hunk 14 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:571]: We just only need to wait one window

File: bin/cml/runner.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (0x2b3bfa0) [reply bin/cml/runner.js]: Yes, everybody agrees with your disagreement and we agreed to leave it as an error.

[the remark this answers is not in the document]
Comment (casperdcl) [reply bin/cml/runner.js]: Yes there was agreement on warning-vs-error.

I didn't see any agreement that suppressing messages was fine?

[the remark this answers is not in the document]
Comment (0x2b3bfa0) [reply bin/cml/runner.js]: > _Yes there was agreement on warning-vs-error._

Yes, there was an agreement on this

> _I didn't see any agreement that suppressing messages was fine?_

No, nobody agreed that suppressing messages was fine

[the remark this answers is not in the document]
Comment (casperdcl) [reply bin/cml/runner.js]: Resolved in 176ccf2

[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply bin/cml/runner.js]: > I didn't see any agreement that hiding the original err.message was fine?

The error message was fixed @casperdcl indeed it disappeared probably overwriting it with your suggestion

**Review by casperdcl — APPROVED** [review]

**Review by 0x2b3bfa0 — APPROVED** [review]
As stated, testing manually all the edge cases covered in this pull request exceeds my current capacity. I have reviewed it statically and looks good, though. :shipit:
