### PR TITLE
Fix cml runner --cloud-gpu to accept `nogpu`

### LINKED ISSUE #746: CML runner error parsing cloud-gpu
There seems to be an error when parsing the cloud-gpu flag. Shortest form of the error can be seen below:

```
dabarnes@ubuntu:~/projects/cml$ docker pull ghcr.io/iterative/cml:latest
...
Digest: sha256:c4a8566b3ef3814524ac5097b53cfcb4e92b3e2f7eb8f2cab51d1e9c07c2ae89
Status: Downloaded newer image for ghcr.io/iterative/cml:latest
ghcr.io/iterative/cml:latest
dabarnes@ubuntu:~/projects/cml$ docker run -it ghcr.io/iterative/cml:latest bash
root@9244604ca392:/home/runner# cml runner --cloud-gpu=nogpu
cml runner

Launch and register a self-hosted runner

Options:
...
Invalid values:
  Argument: cloud-gpu, Given: null, Choices: "nogpu", "k80", "v100", "tesla"
root@9244604ca392:/home/runner# cml --version
0.7.4
root@9244604ca392:/home/runner# 

```

### PR DESCRIPTION
**Pull request by DanielBarnes**
- Closes #746

### CODE REVIEW

**Comment by DanielBarnes** [comment]
Functional test:
```
dabarnes@ubuntu:~/projects/cml$ ./bin/cml.js runner \
>     --single \
>     --log=debug \
>     --idle-timeout=1800 \
>     --token=xxx \
>     --cloud=gcp \
>     --cloud-region=us-west \
>     --cloud-type=m \
>     --cloud-gpu=nogpu \
>     --repo=xxx \
>     --driver=github \
>     --cloud-hdd-size=10
info: Preparing workdir /home/dabarnes/.cml/cml-2g7sdfdtiy...
info: Deploying cloud runner plan...
info: Terraform apply...
info: {"awsSecurityGroup":null,"cloud":"gcp","driver":"github","id":"iterative-34qzkcov8n4ws","idleTimeout":1800,"image":null,"instanceGpu":null,"instanceHddSize":10,"instanceIp":"xxx","instanceLaunchTime":"2021-09-24 09:05:45.397746969 -0700 PDT m=+28.798050565","instanceType":"m","labels":"cml","name":"cml-2g7sdfdtiy","region":"us-west","repo":"xxx","single":true,"spot":false,"spotPrice":-1,"timeouts":null}
```

**Review by 0x2b3bfa0 — APPROVED** [review]

File: bin/cml/runner.js [hunk 1]
```diff
@@ -469,7 +469,7 @@ exports.builder = (yargs) =>
       },
       cloudGpu: {
         type: 'string',
-        choices: ['nogpu', 'k80', 'v100', 'tesla'],
+        choices: ['nogpu', 'k80', 'v100', 'tesla', null],
```
Comment (DavidGOrtega) [inline bin/cml/runner.js:472]: Interesting that this is not working. I was as far as I remember. Maybe using ```undefined``` in the coerce function do the trick? If thats the case maybe is better than null explicitly which is going to be a difficult type to setup

Comment (DanielBarnes) [reply bin/cml/runner.js:472]: I tried changing the value and it seemed that if the result of the coerce function isn't in the choices array then it fails.
My very first patch was to set it to `'nogpu'` instead of null which worked fine.
I opted to add `null` as an option instead to preserve the truthy/falsy behavior in ternary statements.

Comment (DanielBarnes) [reply bin/cml/runner.js:472]: I'll try this and we can see.
```js
        choices: ['nogpu', 'k80', 'v100', 'tesla'],
        coerce: (val) => (val === 'nogpu' ? undefined : val),

```

Comment (DavidGOrtega) [reply bin/cml/runner.js:472]: Thats what I suggested

Comment (DanielBarnes) [reply bin/cml/runner.js:472]: @DavidGOrtega It looks like `undefined` behaves as expected, Im going to do a full test in our gcp env and if it works as expected I'll update the PR.

Comment (0x2b3bfa0) [reply bin/cml/runner.js]: See also https://github.com/yargs/yargs/issues/756

**Comment by DanielBarnes** [comment]
Updated to use `undefined` vs `null` works as expected from my test:
```
dabarnes@ubuntu:~/projects/cml$ ./bin/cml.js runner \
>     --single \
>     --log=debug \
>     --idle-timeout=1800 \
>     --token=xxx\
>     --cloud=gcp \
>     --cloud-region=us-west \
>     --cloud-type=m \
>     --cloud-gpu=nogpu \
>     --repo=xxx \
>     --driver=github \
>     --cloud-hdd-size=10
info: Preparing workdir /home/dabarnes/.cml/cml-jnnd5x6sq0...
info: Deploying cloud runner plan...
info: Terraform apply...
info: {"awsSecurityGroup":null,"cloud":"gcp","driver":"github","id":"iterative-2v4cyhm47w2q7","idleTimeout":1800,"image":null,"instanceGpu":null,"instanceHddSize":10,"instanceIp":"xxx","instanceLaunchTime":"2021-09-24 11:41:41.997215239 -0700 PDT m=+24.104635525","instanceType":"m","labels":"cml","name":"cml-jnnd5x6sq0","region":"us-west","repo":"xxx","single":true,"spot":false,"spotPrice":-1,"timeouts":null}

```

File: bin/cml/runner.js (hunk 1 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js]: > @DavidGOrtega It looks like undefined behaves as expected, Im going to do a full test in our gcp env and if it works as expected I'll update the PR.

@DanielBarnes that was my intuition, since its allowing you to not set it, I would say that this worked also with null previously, but not sure... JS and its non "Good parts" 🙏

Comment (DanielBarnes) [reply bin/cml/runner.js]: > JS and its non "Good parts" 🙏
🤣

**Comment by 0x2b3bfa0** [comment]
Thank you very much, @DanielBarnes!

**Comment by DavidGOrtega** [comment]
> Thank you very much, @DanielBarnes!

I subscribe!!! Thanks @DanielBarnes
