### PR TITLE
Runner edge cases improvements

### LINKED ISSUE #1025: `runner` `-single` restarts the workflows
I have stated that when --single param is used the we restart the workflow if 'no-retry' is set due to lost communication with the runner

### LINKED ISSUE #1037: Oddities in runner log parsing/detecting events
Error parsing is making the runner to fail in GH having scenarios like:
 - runners never ending
 - runners being terminated at idletime even with ongoing jobs 

To avoid them we had to include defensive code that was checking gh jobs. Expensive and also flaky

### PR DESCRIPTION
**Pull request by DavidGOrtega**
The purpose is to remove unwanted "driver" edge cases maintenance and refactor error handling.

 - Handles `--tfResource` inside `runLocal` where it belongs
 - Removes unnecessary try and catch preparing the `workdir` folder due to [recursive param](https://nodejs.org/api/fs.html#fspromisesmkdirpath-options)
 - Removes GH special handler to check jobs relying in log parsing
 - Refactors runner timer logic to be located just only within the setTimeout
 - Fixes error handling in shutdown making effective reason in graceful termination opposed to unhandled error adding the latter for non 0 terminated and/or lost communication with underlying runner
 - Minor: reordering of params putting runner, cloud and hidden.
 - closes #1025 
 - closes #1037 Refactor`parseRunnerLog`. 
    - GH was failing due to exceptional message parsing. 
    - toString('utf8') catch is removed making the runner to die if an error happens while the parsing is happening
    - Handles multiple logs thrown by the runner with a basic regex rules engine
  - Adds `unhandledRejection` and `uncaughtException` termination handler
  - closes https://github.com/iterative/cml/issues/671

### CODE REVIEW

**Comment by DavidGOrtega** [comment]
GL logs can fail because sometime two logs can come toguether, hence JSON parse fails

```sh
info: Preparing workdir /Users/davidgortega/.cml/cml-yrd0icvfjg...
info: Launching gitlab runner
warn: SpotNotifier can not be started.
{"arch":"amd64","level":"info","msg":"Runtime platform","os":"darwin","pid":75487,"revision":"febb2a09","time":"2022-06-04T13:20:38+02:00","version":"15.0.0"}

{"level":"info","msg":"Starting runner for https://gitlab.com with token f9z4UpXQ ...","time":"2022-06-04T13:20:38+02:00"}

info: runner status {"date":"2022-06-04T11:20:38.352Z","repo":"https://gitlab.com/DavidGOrtega/fashion-mnist","status":"ready"}
{"job":2546676556,"level":"info","msg":"Checking for jobs... received","repo_url":"https://gitlab.com/DavidGOrtega/fashion-mnist.git","runner":"f9z4UpXQ","time":"2022-06-04T13:21:39+02:00"}

info: runner status {"date":"2022-06-04T11:21:39.654Z","job":2546676556,"repo":"https://gitlab.com/DavidGOrtega/fashion-mnist","status":"job_started"}
{"job":2546676556,"level":"warning","msg":"Failed to pull image with policy \"always\": failed to register layer: Error processing tar file(exit status 1): write /usr/lib/go-1.18/pkg/linux_amd64/cmd/go/internal/load.a: no space left on device (manager.go:203:77s)","project":27939020,"runner":"f9z4UpXQ","time":"2022-06-04T13:22:57+02:00"}

{"duration_s":77.934181805,"job":2546676556,"level":"warning","msg":"Job failed: failed to pull image \"iterativeai/cml:0-dvc2-base1\" with specified policies [always]: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/go-1.18/pkg/linux_amd64/cmd/go/internal/load.a: no space left on device (manager.go:203:77s)\n","project":27939020,"runner":"f9z4UpXQ","time":"2022-06-04T13:22:57+02:00"}

info: runner status {"date":"2022-06-04T11:22:57.591Z","job":2546676556,"repo":"https://gitlab.com/DavidGOrtega/fashion-mnist","status":"job_ended","success":false}
info: runner status {"reason":"single job","status":"terminated"}
info: Unregistering runner cml-yrd0icvfjg...
{"error":"failed to pull image \"iterativeai/cml:0-dvc2-base1\" with specified policies [always]: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/go-1.18/pkg/linux_amd64/cmd/go/internal/load.a: no space left on device (manager.go:203:77s)","level":"error","msg":"Failed to process build","time":"2022-06-04T13:22:59+02:00"}
{"level":"info","msg":"This runner has processed its build limit, so now exiting","time":"2022-06-04T13:22:59+02:00"}

error: unhandledRejection: Unexpected token { in JSON at position 359
SyntaxError: Unexpected token { in JSON at position 359
    at JSON.parse (<anonymous>)
    at Gitlab.runnerParseLog (/Users/davidgortega/Documents/projects/@iterative/cml/src/drivers/gitlab.js:250:53)
    at CML.parseRunnerLog (/Users/davidgortega/Documents/projects/@iterative/cml/src/cml.js:274:27)
    at Socket.dataHandler (/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml/runner.js:244:27)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:303:12)
    at readableAddChunk (_stream_readable.js:279:9)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {"date":"Sat Jun 04 2022 13:22:59 GMT+0200 (Central European Summer Time)","error":{},"exception":true,"os":{"loadavg":[3.71484375,3.4228515625,3.07763671875],"uptime":1200249},"process":{"argv":["/usr/local/Cellar/node/14.8.0/bin/node","/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml.js","runner","--labels","cml","--single","--idle-timeout","500","--repo","https://gitlab.com/DavidGOrtega/fashion-mnist","--token","kZeyQWegQyAHRcVKB2zo"],"cwd":"/Users/davidgortega/Documents/projects/@iterative/cml","execPath":"/usr/local/Cellar/node/14.8.0/bin/node","gid":20,"memoryUsage":{"arrayBuffers":1550730,"external":19824409,"heapTotal":30584832,"heapUsed":25139296,"rss":66179072},"pid":75380,"uid":501,"version":"v14.8.0"},"stack":"SyntaxError: Unexpected token { in JSON at position 359\n    at JSON.parse (<anonymous>)\n    at Gitlab.runnerParseLog (/Users/davidgortega/Documents/projects/@iterative/cml/src/drivers/gitlab.js:250:53)\n    at CML.parseRunnerLog (/Users/davidgortega/Documents/projects/@iterative/cml/src/cml.js:274:27)\n    at Socket.dataHandler (/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml/runner.js:244:27)\n    at Socket.emit (events.js:314:20)\n    at addChunk (_stream_readable.js:303:12)\n    at readableAddChunk (_stream_readable.js:279:9)\n    at Socket.Readable.push (_stream_readable.js:218:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)","trace":[{"column":null,"file":null,"function":"JSON.parse","line":null,"method":"parse","native":false},{"column":53,"file":"/Users/davidgortega/Documents/projects/@iterative/cml/src/drivers/gitlab.js","function":"Gitlab.runnerParseLog","line":250,"method":"runnerParseLog","native":false},{"column":27,"file":"/Users/davidgortega/Documents/projects/@iterative/cml/src/cml.js","function":"CML.parseRunnerLog","line":274,"method":"parseRunnerLog","native":false},{"column":27,"file":"/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml/runner.js","function":"Socket.dataHandler","line":244,"method":"dataHandler","native":false},{"column":20,"file":"events.js","function":"Socket.emit","line":314,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js","function":"addChunk","line":303,"method":null,"native":false},{"column":9,"file":"_stream_readable.js","function":"readableAddChunk","line":279,"method":null,"native":false},{"column":10,"file":"_stream_readable.js","function":"Socket.Readable.push","line":218,"method":"push","native":false},{"column":23,"file":"internal/stream_base_commons.js","function":"Pipe.onStreamRead","line":188,"method":"onStreamRead","native":false}]}
info:   Success
```

**Comment by DavidGOrtega** [comment]
very hard to reproduce

**Comment by dacbd** [comment]
Seems to be fine with my basic actions test sweet I've been able to compose so far: 
image

File: bin/cml/runner.js [hunk 1]
```diff
@@ -245,63 +273,25 @@ const runLocal = async (opts) => {
   proc.stderr.on('data', dataHandler);
   proc.stdout.on('data', dataHandler);
   proc.on('disconnect', () =>
-    shutdown({ ...opts, reason: `runner disconnected` })
-  );
-  proc.on('close', (exit) =>
-    shutdown({ ...opts, reason: `runner closed with exit code ${exit}` })
+    shutdown({ ...opts, error: new Error('runner disconnected') })
```
Comment (dacbd) [inline bin/cml/runner.js:276]: I believe this event only triggers if we call `subprocess.disconnect()` ourselves? and does not necessarily mean `"runner disconnected"` I feel that message has a network connotation and not an `IPC` channel has stopped sending messages.

File: bin/cml/runner.js [hunk 2]
```diff
@@ -245,63 +273,25 @@ const runLocal = async (opts) => {
...
-          clearInterval(watcher);
-        } else {
-          RUNNER_TIMER = 0;
-        }
+        shutdown({ ...opts, reason: `timeout:${idleTimeout}` });
+        clearInterval(watcher);
       }
 
-      RUNNER_TIMER++;
+      RUNNER_TIMER = idle ? RUNNER_TIMER + 1 : 0;
```
Comment (dacbd) [inline bin/cml/runner.js:294]: Maybe some in code comments for future readers as this seems to a be a hotspot.
```suggestion
       // RUNNER_TIMER only increments if runner is idle
      RUNNER_TIMER = idle ? RUNNER_TIMER + 1 : 0;
```

File: bin/cml/runner.js [hunk 3]
```diff
@@ -333,23 +323,26 @@ const runLocal = async (opts) => {
 };
 
 const run = async (opts) => {
+  process.on('unhandledRejection', (reason) =>
```
Comment (dacbd) [inline bin/cml/runner.js:326]: the event `uncaughtException` should also receive these events?

File: bin/cml/runner.js [hunk 4]
```diff
@@ -333,23 +323,26 @@ const runLocal = async (opts) => {
...
+    shutdown({ ...opts, error: new Error(reason) })
```
Comment (dacbd) [inline bin/cml/runner.js:327]:
```suggestion
    shutdown({ ...opts, error: reason instanceof Error ? reason : new Error(reason) })
```

File: src/cml.js [hunk 5]
```diff
@@ -257,77 +257,38 @@ class CML {
...
-          log.status = 'ready';
-        }
+    const logs = [];
+    const entities = await getDriver(this).runnerParseLogEntities();
+    for (const [entity, rule] of Object.entries(entities)) {
+      const regex = new RegExp(rule);
+      if (regex.test(data)) {
+        const date = new Date();
+        const log = {
+          id: 'dummy',
```
Comment (dacbd) [inline src/cml.js:273]: id not used/overwritten? Where does `log.job` get set?
ref: https://github.com/iterative/cml/blob/fbec7b00d8f2a6034a8e5fd85eb44e84dd53c1c2/bin/cml/runner.js#L254-L257

File: src/cml.js [hunk 6]
```diff
@@ -257,77 +257,38 @@ class CML {
...
-          log.status = 'job_started';
-        } else if (data.includes('completed with result')) {
-          log.job = id;
-          log.status = 'job_ended';
-          log.success = data.includes('Succeeded');
-        } else if (data.includes('Listening for Jobs')) {
-          log.status = 'ready';
-        }
+    const logs = [];
+    const entities = await getDriver(this).runnerParseLogEntities();
```
Comment (0x2b3bfa0) [inline src/cml.js:267]: Same here and all the `entity` below: maybe a bit more descriptive?

**Review by 0x2b3bfa0 — COMMENTED** [review]
Nitpicks 💅🏼

File: src/drivers/bitbucket_cloud.js [hunk 7]
```diff
@@ -266,6 +266,15 @@ class BitbucketCloud {
     return href;
   }
 
+  runnerParseLogEntities() {
```
[the remark this answers is not in the document]
Comment (dacbd) [reply src/drivers/bitbucket_cloud.js:269]: I agree, I feel `runnerStatusPatterns` is clearer

File: bin/cml/runner.js [hunk 8]
```diff
@@ -128,6 +122,8 @@ const runCloud = async (opts) => {
       workdir
     } = opts;
 
+    await tf.checkMinVersion();
```
[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply bin/cml/runner.js:125]: Its done that way @dacbd If you follow up this is going to happen if you launch either by a local runner with a tfresource or a cloud runner. All that is wrapped by a catch that is calling the termination passing the error and this one logging it

File: bin/cml/runner.js [hunk 9]
```diff
@@ -211,24 +208,55 @@ const runCloud = async (opts) => {
...
-    } else if (log && log.status === 'job_ended') {
-      const { job: jobId } = log;
-      RUNNER_JOBS_RUNNING = RUNNER_JOBS_RUNNING.filter(
-        (job) => job.id !== jobId
-      );
-      RUNNER_TIMER = 0;
+    const logs = await cml.parseRunnerLog({ data });
+    for (const idx in logs) {
+      const log = logs[idx];
+      log && winston.info('runner status', log);
```
[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply bin/cml/runner.js:247]: Good catch. log is never going to be undefined at this point. that check is not needed anymore.

File: bin/cml/runner.js (hunk 1 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:276]: No, disconnected happens when by any meaning we do not have access to the runner's IPC channel

File: bin/cml/runner.js (hunk 2 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:294]: A better comment indeed is `if working we reset the timer`
I consider comments a very bad practice unless is a link to a discussion and not very fan of that either

File: bin/cml/runner.js (hunk 3 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:326]: No, uncaught is for not promisified errors while the other captures promises. Both are needed

File: bin/cml/runner.js (hunk 4 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:327]: Its not going to be an Error unless an Error is what is rejected (uncommon) 
https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event

In any case for your curiosity 😉 
```js
const err = new Error('hi')
const err2 = new Error(err)
console.log(err2.message)
```

File: src/cml.js (hunk 5 above)
Comment (DavidGOrtega) [reply src/cml.js:273]: id is `dummy` right now for every SCM, all the same

File: src/drivers/bitbucket_cloud.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply src/drivers/bitbucket_cloud.js:269]: Probably my NLP experience here the guilty. Im using a pretty basic regex mechanism and of course came to my mind StandfordNER. We indeed are looking to extract named entities from raw text, the problem is that our engine is not that sophisticated 😁

File: bin/cml/runner.js [hunk 10]
```diff
@@ -211,24 +208,55 @@ const runCloud = async (opts) => {
...
-      RUNNER_JOBS_RUNNING.push({ id: log.job, date: log.date });
-    } else if (log && log.status === 'job_ended') {
-      const { job: jobId } = log;
-      RUNNER_JOBS_RUNNING = RUNNER_JOBS_RUNNING.filter(
-        (job) => job.id !== jobId
-      );
-      RUNNER_TIMER = 0;
+    const logs = await cml.parseRunnerLog({ data });
+    for (const idx in logs) {
+      const log = logs[idx];
```
[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply bin/cml/runner.js:246]: What we have in return within the `for` is not the log but the array index @0x2b3bfa0

[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply bin/cml/runner.js:246]: True! Nice catch

File: src/drivers/bitbucket_cloud.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply src/drivers/bitbucket_cloud.js:269]: After the reasons that I gave might sound reasonable to you to stick with that?

File: src/cml.js (hunk 6 above)
Comment (DavidGOrtega) [reply src/cml.js:267]: Same as [here](https://github.com/iterative/cml/pull/1030#discussion_r893162936)

File: src/drivers/bitbucket_cloud.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (0x2b3bfa0) [reply src/drivers/bitbucket_cloud.js:269]: It feels too “creative” for pedestrian software engineering. 🤷🏼‍♂️ Asking @iterative/cml naming machines to break the tie. 🤖

File: bin/cml/runner.js (hunk 2 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:293]: @dacbd

Comment (dacbd) [reply bin/cml/runner.js:293]: Your first pass reading comprehension is better than mine. I'm not suggesting that we comment all over the code.

This particular chunk of logic is a hotspot though and several issues have emanated from the timeout logic and I would prefer it be as explicit as possible even if it adds some lines perhaps this instead:

I have spent numerous hours trying to debug https://github.com/iterative/cml/issues/808 and I'm not convinced the true culprit was ever definitively nailed down

```js
if (idle) {
  RUNNER_TIMER += 1
} else {
  RUNNER_TIMER = 0
}
```

I'll finish with its fine to resolve here and I'm okay with the logic as is, but the next timeout bug I'll be throughing a larger fit about 🙉

File: src/drivers/bitbucket_cloud.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (dacbd) [reply src/drivers/bitbucket_cloud.js:269]: name for function, right now its only function is determine runnerStatus

[the remark this answers is not in the document]
Comment (casperdcl) [reply src/drivers/bitbucket_cloud.js:269]: +1 for `runnerStatusPatterns` :)

File: bin/cml/runner.js (hunk 1 above)
Comment (dacbd) [reply bin/cml/runner.js:275]: How about this?
```suggestion
    shutdown({ ...opts, error: new Error('runner proccess lost') })
```

If I had an issue and looking at logs and saw an error `runner disconnected` my mind goes to networking not IPC

File: bin/cml/runner.js (hunk 3 above)
Comment (dacbd) [reply bin/cml/runner.js:325]: doesn't really matter but the docs say otherwise https://nodejs.org/dist/latest-v16.x/docs/api/process.html#event-uncaughtexception

File: bin/cml/runner.js (hunk 4 above)
Comment (dacbd) [reply bin/cml/runner.js:326]: https://nodejs.org/dist/latest-v16.x/docs/api/process.html#event-unhandledrejection 
- `reason`  [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)  |  [any](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types) The object with which the promise was rejected (typically an [Error](https://nodejs.org/dist/latest-v16.x/docs/api/errors.html#class-error) object).

File: src/cml.js (hunk 5 above)
Comment (DavidGOrtega) [reply src/cml.js:273]: Its mean to be an id, however that id is only reachable in GL

File: bin/cml/runner.js (hunk 1 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:275]: Ah I see!

File: src/drivers/bitbucket_cloud.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (DavidGOrtega) [reply src/drivers/bitbucket_cloud.js]: done! almost... `runnerLogStatusPatterns` instead

File: bin/cml/runner.js (hunk 3 above)
Comment (DavidGOrtega) [reply bin/cml/runner.js:325]: Umm Its true that it says that... That must be a new change but I can state that the one that captured a bug while writing the new state parser was the `unhandledRejection`

**Review by dacbd — APPROVED** [review]
I am satisfied.

**Comment by DavidGOrtega** [comment]
🤞 any luck here @iterative/cml

**Review by 0x2b3bfa0 — APPROVED** [review]
Expedited static review: looks mergeable to me
