### PR TITLE
Fix publish magic.mgc altered by babel

### LINKED ISSUE #898: cml publish is broken in binary
following #879

```sh
root@0ec50cbf3fbb:/iterative/cml# cml2 publish assets/logo.png 

...
/snapshot/cml/node_modules/@npcz/magic/dist/magic.mgc, 3422: Warning: offset `' invalid
/snapshot/cml/node_modules/@npcz/magic/dist/magic.mgc, 3425: Warning: offset `.' invalid
/snapshot/cml/node_modules/@npcz/magic/dist/magic.mgc, 3427: Warning: offset `.' invalid
/snapshot/cml/node_modules/@npcz/magic/dist/magic.mgc, 3453: Warning: offset `' invalid
/snapshot/cml/node_modules/@npcz/magic/dist/magic.mgc, 3457: Warning: offset `.' invalid
/snapshot/cml/node_modules/@npcz/magic/dist/magic.mgc, 3473: Warning: offset `' invalid
```

### PR DESCRIPTION
**Pull request by DavidGOrtega**
Happens that babel is altering  `magic.mgc` making impossible to just keep the mgc file in the `node_modules` dir.

- closes #898

### CODE REVIEW

**Review by casperdcl — COMMENTED** [review]
wait so we have to put a 7MB binary file in the repo?

There must be another way (e.g. copy to different dir before building binary)

**Comment by DavidGOrtega** [comment]
> There must be another way (e.g. copy to different dir before building binary)

I thought that but the code is going to be uglier. Don't sure if its going to be a nice tradeoff

**Comment by DavidGOrtega** [comment]
@casperdcl updated 🤞

File: src/utils.js [hunk 1]
```diff
@@ -27,11 +27,14 @@ const exec = async (command) => {
...
-    'node_modules/@npcz/magic/dist/magic.mgc'
-  );
+  let magicFile = PATH.join(__dirname, '../assets/magic.mgc');
+  if (!fs.existsSync(magicFile))
+    magicFile = PATH.join(
+      __dirname,
+      '../node_modules/@npcz/magic/dist/magic.mgc'
+    );
+
+  FileMagic.magicFile = magicFile;
```
Comment (0x2b3bfa0) [inline src/utils.js:37]: If you upgrade to [`@npcz/magic@1.3.12`](https://github.com/npcz/magic/releases/tag/v1.3.12) this code can be simplified to the following:

```suggestion
  if (fs.existsSync(magicFile)) FileMagic.magicFile = magicFile; 
```

See https://github.com/npcz/magic/issues/10 for more information.

File: src/utils.js [hunk 2]
```diff
@@ -27,11 +27,14 @@ const exec = async (command) => {
 
 const mimeType = async (opts) => {
   const { path, buffer } = opts;
-  FileMagic.magicFile = PATH.join(
-    __dirname,
-    '..',
-    'node_modules/@npcz/magic/dist/magic.mgc'
-  );
+  let magicFile = PATH.join(__dirname, '../assets/magic.mgc');
+  if (!fs.existsSync(magicFile))
```
Comment (0x2b3bfa0) [inline src/utils.js:31]: “[_No sync functions. Please use async_](https://github.com/iterative/cml/pull/391#discussion_r574623597)” 😉 I guess that, in this specific case, using a synchronous function is easier than [using a deprecated one](https://nodejs.org/api/fs.html#fsexistspath-callback), though.

**Review by casperdcl — APPROVED** [review]

File: src/utils.js (hunk 2 above)
Comment (DavidGOrtega) [reply src/utils.js:31]: Yes, we have a couple of sync in the code due to not very nice async counterparts and the side effect is not horrible due to the nature of the command (just only publish one file) VS a more demanding command like the runner

File: src/utils.js (hunk 1 above)
Comment (0x2b3bfa0) [reply src/utils.js:37]: https://github.com/iterative/cml/pull/901
