### PR TITLE
`github-send-check` usage warnings

### LINKED ISSUE #829: cml `send-github-check` is incorrectly using the `repo_token`
The command can only use `GITHUB_TOKEN` within the original IP, non else would work

### PR DESCRIPTION
**Pull request by DavidGOrtega**
I haven't found an optimal approach to this aside warn the user that this command can not be used outside a runner or a Github app. 

- closes #829
- Additionally includes the possibility of changing the status

### CODE REVIEW

File: src/drivers/github.js [hunk 1]
```diff
@@ -165,6 +168,15 @@ class Github {
...
     } = opts;
 
+    const warning =
+      'This command only works inside a Github runner or a Github app.';
+
+    if (!CI || TPI_TASK) winston.warn(warning);
+    if (GITHUB_TOKEN && GITHUB_TOKEN !== this.token)
+      winston.warn(
+        `Your token is different than the GITHUB_TOKEN, this command does not work with PAT. ${warning}`
+      );
```
Comment (casperdcl) [inline src/drivers/github.js:178]: this warning will incorrectly be triggered when using `REPO_TOKEN=<some_app_token>`?

Comment (DavidGOrtega) [reply src/drivers/github.js:178]: Yes, but we cant distinguish between PAT or app token, thats why is just a warning

Comment (DavidGOrtega) [reply src/drivers/github.js:178]: @casperdcl ?

Comment (casperdcl) [reply src/drivers/github.js:178]: something like this?

```suggestion
    if (GITHUB_TOKEN && GITHUB_TOKEN !== this.token && !REPO_TOKEN)
      winston.warn(
        `Your token is different than the GITHUB_TOKEN, this command does not work with PAT. ${warning}`
      );
```

Comment (DavidGOrtega) [reply src/drivers/github.js:178]: No, the warning is just in case you use a PAT instead of a GITHUB_TOKEN

Comment (DavidGOrtega) [reply src/drivers/github.js:178]: The code is OK as it is

Comment (casperdcl) [reply src/drivers/github.js:178]: but what happens if someone has an env with both `REPO_TOKEN` and `GITHUB_TOKEN` defined? this is common afaik...

Comment (DavidGOrtega) [reply src/drivers/github.js:178]: It will warn about bad token usage so they have to explicitly set the `--token $GITHUB_TOKEN` in order to make it work. Im not enforcing it always to read GITHUB_TOKEN because  you could actually use this command with a Github App token

**Review by 0x2b3bfa0 — APPROVED** [review]
Looks good to me. Ready for merging, @iterative/cml
