### PR TITLE
cml-publish mime and repo

### LINKED ISSUE #480: cml-publish fails in folders not init by git
as #478 

```sh
Error: Command failed: git config --get remote.origin.url
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at repo_from_origin (/iterative/cml/src/cml.js:15:18)
    at new CML (/iterative/cml/src/cml.js:63:47)
    at run (/iterative/cml/bin/cml-publish.js:28:15)
    at Object.<anonymous> (/iterative/cml/bin/cml-publish.js:86:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 12360,
  stdout: <Buffer >,
  stderr: <Buffer >
}
```

### LINKED ISSUE #518: cml-publish does not support basic text files
Reproduce it:

```sh
echo Hello > world.txt
cml-publish --repo=https://github.com/DavidGOrtega/cml-dvc-test world.txt

Error: Failed guessing mime type of file world.txt
    at mime_type (/iterative/cml/src/utils.js:49:11)
    at async fetch_upload_data (/iterative/cml/src/utils.js:60:16)
    at async upload (/iterative/cml/src/utils.js:69:38)
    at async CML.publish (/iterative/cml/src/cml.js:110:24)
    at async run (/iterative/cml/bin/cml-publish.js:25:18)
```

### PR DESCRIPTION
**Pull request by DavidGOrtega**
- does not need repo for non native
 - Detects also non binary files. 
 - Adds param ```mime-type``` to specify the mime in case the type is incorrect. I.E. ```application/json``` is still now detected as ```text/plain```
 - Adds camelize cleaning the CLI interface
 - aliases ```gitlab-uploads```

```
Usage: cml-publish.js <path to file>

      Options:
        --version                   Show version number                      [boolean]
        --md                        Output in markdown format [title || name](url).
                                                                             [boolean]
        --title, -t                 Markdown title [title](url) or ![](url title).
        --native, --gitlab-uploads  Uses driver's native capabilities to upload assets
                                    instead of CML's storage. Currently only available
                                    for GitLab CI.
        --rm-watermark              Avoid CML watermark.                     [boolean]
        --mime-type                 Specifies the mime-type. If not set guess it from
                                    the content.
        --file, -f                  Append the output to the given file. Create it if
                                    does not exist.
        --repo                      Specifies the repo to be used. If not specified is
                                    extracted from the CI ENV.
        --token                     Personal access token to be used. If not
                                    specified, extracted from ENV REPO_TOKEN,
                                    GITLAB_TOKEN, GITHUB_TOKEN, or BITBUCKET_TOKEN.
        --driver                    If not specify it infers it from the ENV.
                                                         [choices: \\"github\\", \\"gitlab\\"]
        -h                          Show help                                [boolean]"
```

closes #518 
closes #480

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -20,44 +19,34 @@ const exec = async (command) => {
...
-    if (path) ({ mime } = await FileType.fromFile(path));
-    else ({ mime } = await FileType.fromBuffer(buffer));
-
-    return mime;
-  } catch (err) {
-    throw new Error(
-      `Failed guessing mime type of ${path ? `file ${path}` : `buffer`}`
-    );
-  }
+  return new Promise((resolve, reject) => {
```
Comment (0x2b3bfa0) [inline src/utils.js:23]: Why `return new Promise` instead of taking advantage of `async` to `throw` and `return` instead of calling the `reject` and `resolve` functions?

Comment (DavidGOrtega) [reply src/utils.js:23]: The library does not support promises. When that happen you have to promisify the function.

Comment (0x2b3bfa0) [reply src/utils.js:23]: I see, what a pity!

**Review by 0x2b3bfa0 — APPROVED** [review]

**Review by casperdcl — APPROVED** [review]
