### PR TITLE
Automatically detect GitLab API base address

### LINKED ISSUE #463: Support GitLab url with custom path
When gitlab is exposed on the path `https://mydomain.com/gitlab` cml cannot work with such types of urls - the generated api endpoint is `https://mydomain.com/api/v4` but should be `https://mydomain.com/gitlab/api/v4` 

Also it can be appropriate to support custom ports in the urls

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
This pull request should fix #463, where a GitLab instance served from a path different from the server root wouldn't be interpreted correctly. It feels [a bit complicated](https://wiki.c2.com/?BigBallOfMud) for my taste, but should perform as expected.

### CODE REVIEW

File: src/drivers/gitlab.js [hunk 1]
```diff
@@ -45,7 +72,7 @@ class Gitlab {
 
   async upload(opts = {}) {
     const { project_path, repo } = this;
-    const endpoint = `/projects/${project_path}/uploads`;
+    const endpoint = `${await this.detect_api_v4()}/projects/${project_path}/uploads`;
```
Comment (DavidGOrtega) [inline src/drivers/gitlab.js:75]: Why not leave this and subsequent methods intact and recalculate the api_v4 within the request function ?

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]

File: src/drivers/gitlab.js (hunk 1 above)
Comment (0x2b3bfa0) [reply src/drivers/gitlab.js:75]: Because we're also using the `request` function to detect the right address. Your suggested modification is rather elegant, but we would need to resolve this circular dependency somehow.

Comment (DavidGOrtega) [reply src/drivers/gitlab.js:75]: You could pass endpoint as you where or url in opts. If endpoint is passed you call the detect_api... that is returning the proper one if its calculated if url is passed you just take the url

Comment (DavidGOrtega) [reply src/drivers/gitlab.js:75]: @0x2b3bfa0

Comment (0x2b3bfa0) [reply src/drivers/gitlab.js]: Nice! 🙏

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, please take a look to the new changes.

File: src/drivers/gitlab.js [hunk 2]
```diff
@@ -149,13 +171,18 @@ class Gitlab {
   }
 
   async request(opts = {}) {
-    const { token, api_v4 } = this;
+    const { token } = this;
     const { endpoint, method = 'GET', body, raw } = opts;
+    let { url } = opts;
 
-    if (!endpoint) throw new Error('Gitlab API endpoint not found');
+    if (endpoint) {
```
Comment (DavidGOrtega) [inline src/drivers/gitlab.js:178]:
```js
if (endpoint) {
      this.api_v4 = this.api_v4 || (await this.detect_api_v4());
      url = `${this.api_v4}${endpoint}`;
    } 

if (!url) throw new Error('Gitlab API url not found');
```

Comment (DavidGOrtega) [reply src/drivers/gitlab.js:178]: dryer and is a validation in any circumstance

**Review by DavidGOrtega — CHANGES_REQUESTED** [review]

File: src/drivers/gitlab.js (hunk 2 above)
Comment (DavidGOrtega) [reply src/drivers/gitlab.js:178]: @0x2b3bfa0

Comment (0x2b3bfa0) [reply src/drivers/gitlab.js:178]: 👌 🙏

**Comment by 0x2b3bfa0** [comment]
🔔 @DavidGOrtega

**Comment by DavidGOrtega** [comment]
Looks good. Are you going to do a release of merge straight against master? @0x2b3bfa0

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, unless you want otherwise, I'll release v0.3.3 for consistency.

**Review by DavidGOrtega — APPROVED** [review]
