### PR TITLE
Fix `cml pr create` on subdirectories

### LINKED ISSUE #1344: Pull request creation not working on subdirectories
It looks like `cml pr create` is failing to detect files when running from directories other than the repository root.

```console
$ cd subdirectory
$ date > file
$ cml pr create file # same if the path is `.`
warn: Input files are not affected. Nothing to do.
undefined
```

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Closes #1344

### CODE REVIEW

**Review by dacbd — CHANGES_REQUESTED** [review]
is this test format not correct? it seems this doesn't work? https://github.com/iterative/cml-playground/actions/runs/4115453808/jobs/7104182705

**Comment by 0x2b3bfa0** [comment]
@dacbd, it looks like your test is indeed wrong: no files were modified in the subdirectory.

```diff
- echo "$(date +%s%N) - modication" >> cml.log
+ echo "$(date +%s%N) - modication" >> examples/cml.log
```

**Review by dacbd — DISMISSED** [review]
g2g fixed test

File: src/cml.js [hunk 1]
```diff
@@ -625,3 +631,4 @@ module.exports = {
   GIT_USER_NAME,
   GIT_REMOTE
 };
+
```
Comment (dacbd) [inline src/cml.js:634]:
```suggestion
```

**Review by dacbd — APPROVED** [review]
